### ISSUE TITLE
in webs seems like a "mi tele"

### ISSUE THREAD

**Issue by leonfrr** [aabilio/PyDownTV2#1]
Helo,

I just tried to download to telecinco's web (mitele.es) and i read the instructións to proceed.
I'm working with chrome.
I click on the alt button but it doesnt works.
But if I tried from the video is running on the web "mitele.es", when i click right the download is like mp4.
Works if the video are initializing in the web.

sorry for my English

a greeting

**Comment by vhela** [comment]
Hi I am trying to download a video from "my TV" and not let me from Chrome or from firefox or from explorer. I followed the instructions but still does not let me download

also sorry for my English

**Comment by aabilio** [comment]
Si habláis castellano adelante, que soy gallego de toda la vida :P 
Las instrucciones descritas en la wiki a mi me funcionan bien, solo que hay que ser en algunos casos bastante rápido, sobre todo, si PyDownTV ha tardado en devolver el enlace...
La verdad que no entiendo muy bien qué me queréis decir, a ver si me podéis volver a comentar ;)

Saludos.
