### ISSUE TITLE
Eitb.tv: WARNING: Unknown protocol!  ERROR: You must specify a playpath or url

### ISSUE THREAD

**Issue by zikinkeriak** [aabilio/PyDownTV2#10]
Buenas,

Al intentar descargarme un vídeo de eitb.tv me sale el error de abajo.

No se como ponerle la categoría de bug ni la versión de la web. Lo siento.

Muchas gracias!

WARNING: Unknown protocol!

ERROR: You must specify a playpath (--playpath) or url (-r "rtmp://host[:port]/p
laypath") containing a playpath
El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del v
olumen no son correctos."slist" no se reconoce como un comando interno o externo
,
programa o archivo por lotes ejecutable.
"auth" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"aifp" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"slist" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"auth" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"aifp" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"videoId" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"lineUpId" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"pubId" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"playerId" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"slist" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"auth" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"aifp" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"videoId" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by aabilio** [comment]
Me puedes decir con qué vídeo en concreto te pasa eso?

**Comment by zikinkeriak** [comment]
El video es este:
http://www.eitb.tv/es/#/video/1941133202001

Gracias!

**Comment by aabilio** [comment]
A mi me descarga perfectamente con el comando proporcionado por PyDownTV: rtmpdump --rtmp 'rtmp://cp150446.edgefcs.net/ondemand/&mp4:102076681001/102076681001_1942097066001_107738-20121102-150921.mp4?**nn**=1497926354001&slist=102076681001/&auth=daEa0c9aZdSbJa0dLcAdNbBb5bjcea8aRc0-brhcKa-bWG-mnyAssvx_yCAt_GFEz_EtC&aifp=bcosuds' --app='ondemand?**nn**=1497926354001&slist=102076681001/&auth=daEa0c9aZdSbJa0dLcAdNbBb5bjcea8aRc0-brhcKa-bWG-mnyAssvx_yCAt_GFEz_EtC&aifp=bcosuds&videoId=1941133202001&lineUpId=&pubId=102076681001&playerId=893448935001' --swfUrl='http://admin.brightcove.com/viewer/us20121213.1025/federatedVideoUI/BrightcovePlayer.swf?uid=1355746343102' --playpath='mp4:102076681001/102076681001_1942097066001_107738-20121102-150921.mp4?**nn**=1497926354001&slist=102076681001/&auth=daEa0c9aZdSbJa0dLcAdNbBb5bjcea8aRc0-brhcKa-bWG-mnyAssvx_yCAt_GFEz_EtC&aifp=bcosuds&videoId=1941133202001' --pageUrl='http://www.eitb.tv/es/#/video/1941133202001' -o 'DBH_-1-.mp4'

Yo creo que el problema puede estar a la hora de colocar de copiar/pegar el comando en la consola. Puede ser que algunas comillas cambien de formato. Podrías intentar cambiar todas las comillas simples que rodean los argumentos a mano, es decir, eliminando la que pegas y poniendo a mano una (la simple, la de debajo del signo de interrogación). Es para ir probando. Tambien puedes probar a pegar el comando que pegué yo en este comentario a ver..

**Comment by zikinkeriak** [comment]
He hecho los dos intentos y sigue sin dejarme.

**Comment by zikinkeriak** [comment]
He instalado en linux y si que me funciona, pero en windows no. No se que puede ser....

**Comment by aabilio** [comment]
Tengo que probarlo en una instalación de Windows que tengo para ver... A ver si lo puedo ver luego ;)

**Comment by aabilio** [comment]
Acabo de comprobar desde Windows 7 que efectivamente el problema está en las comillas simples. He cambiado todas y cada una de ellas por comillas dobles normales (las que están encima del dos) y me ha descargado el vídeo correctamente.
Tendré que ver si cambiar las comillas simples por las dobles por defecto (es que las dobles se suelen copiar mal en  la terminal...).

**Comment by agus20** [comment]
Hola.

Yo introduzco:
C:\Videos>rtmpdump --rtmp "rtmp://cp101675.edgefcs.net/ondemand/&mp4:23/10207668
1001/201302/2901/102076681001_2191259861001_135699-20130226-192714.mp4?**nn**=15
45806548001&slist=23/102076681001/201302/1083/;23/102076681001/201302/2741/;23/1
02076681001/201302/2901/&auth=daEbHb8dgaHb.aXbfdEasdSdjdkcrbdbodt-brno8W-bWG-BBx
p_EAn_ALwD_DmJ&aifp=rtmpeuds17" --app="ondemand?**nn**=1545806548001&slist=23/10
2076681001/201302/1083/;23/102076681001/201302/2741/;23/102076681001/201302/2901
/&auth=daEbHb8dgaHb.aXbfdEasdSdjdkcrbdbodt-brno8W-bWG-BBxp_EAn_ALwD_DmJ&aifp=rtm
peuds17&videoId=2191163609001&lineUpId=&pubId=102076681001&playerId=893448935001
" --swfUrl="http://admin.brightcove.com/viewer/us20121213.1025/federatedVideoUI/
BrightcovePlayer.swf?uid=1355746343102" --playpath="mp4:23/102076681001/201302/2
901/102076681001_2191259861001_135699-20130226-192714.mp4?**nn**=1545806548001&s
list=23/102076681001/201302/1083/;23/102076681001/201302/2741/;23/102076681001/2
01302/2901/&auth=daEbHb8dgaHb.aXbfdEasdSdjdkcrbdbodt-brno8W-bWG-BBxp_EAn_ALwD_Dm
J&aifp=rtmpeuds17&videoId=2191163609001" --pageUrl="http://www.eitb.tv/es/#/vide
o/2191163609001" -o "El_Conquistador_del_Fin_del_Mundo_2010-2013_-9-.mp4"

y me da los siguientes errores:

RTMPDump v2.3
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
WARNING: Unknown protocol!

ERROR: You must specify a playpath (--playpath) or url (-r "rtmp://host[:port]/p
laypath") containing a playpath
El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del v
olumen no son correctos."slist" no se reconoce como un comando interno o externo
,
programa o archivo por lotes ejecutable.
"auth" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"aifp" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"slist" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"auth" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"aifp" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"videoId" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"lineUpId" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"pubId" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"playerId" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"slist" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"auth" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"aifp" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"videoId" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

¿Que es lo que hago mal?

Gracias

**Comment by aabilio** [comment]
@agus20 la respuesta está justo antes de tu pregunta ;)
A ver si lo arreglo para que directamente salgan las comillas simples en estos casos.
Saludos.

**Comment by agus20** [comment]
Hola.
Pydown da el resultado con ' yo lo cambio a " pero me da los errores que
puse.

**Comment by aabilio** [comment]
A mí en Mac me descarga con las dos formas, y en Windows a veces me falla con las comillas simples, pero si las paso a comillas dobles siempre me funciona. No sé qué puede estar pasando entonces..

**Comment by aabilio** [comment]
Como a mí en MacOS y en GNU/Linux siempre me va bien con las comillas simples, y se han reportado  que en Windows a veces falla (y yo lo he comprobado un par de veces con Windows 7) ahora PyDownTV si detecta que te conectas a través de Windows proporcionará el comando directamente utilizando comillas dobles. A ver cómo se pegan en la consola de Windows (ya que sé de casos de que cuando se utilizaban las comillas dobles no se pegaban bien en la consola y se cambiaban por otras comillas)...

Espero algún reporte por vuestra parte. Saludos.
