### ISSUE TITLE
Error con videos de Canal +

### ISSUE THREAD

**Issue by zochre** [aabilio/PyDownTV2#101]
Hola a todos/as:

Desde hace algunos días, he comprobado que ya no funcionan los enlaces de los videos subidos a la web de Canal +

Una URL de ejemplo es la siguiente: http://canalplus.es/play/video.html?xref=20140112plucanftb_13.Ves

Al intentar obtener el link directo al video, aparece el siguiente mensaje:

![captura de pantalla 2014-02-02 a las 23 36 37](https://f.cloud.github.com/assets/6570326/2061568/8ce3a488-8c5a-11e3-8551-cc636fca2b7a.jpg)

Desde la API, muestra el siguiente texto:

{"exito": false, "mensaje": "Error desconocido"}

Gracias de antemano, un saludo.

**Comment by aabilio** [comment]
He estado tocando un poco el canal y parece que vuelve a descargar.
Un par de pruebas: http://web.pydowntv.com/?url=http%3A//canalplus.es/play/video.html%3Fxref%3D20140112plucanftb_13.Ves y http://www.pydowntv.com/?url=http%3A//canalplus.es/play/video.html%3Fid%3D1102331%26media%3DNF963272%26cc%3DPLTVPR 

[Commit: https://github.com/aabilio/PyDownTV2/commit/3ca9bc50859993cff97982c125056a77507b7b97]

**Comment by zochre** [comment]
¡Perfecto!

Muchas gracias :)
