### ISSUE TITLE
Cambios tele5                                                                                                        bug

### ISSUE THREAD

**Issue by lusoma** [aabilio/PyDownTV2#102]
desde hace no mas de 15 dias no me va la descarga.Lo hacia con Opera,copiando de la caché pero ahora observo que guarda el video en multiples trozos .tmp de maximo 500 kbs.
  Trabajo con Ubuntu (kubuntu) y poco a poco han ido desapareciendo las posibilidades,por ejemplo copiando de /proc/id.proceso/fd/xx . Ya no aparece tampoco ahí.
        En tu web,busca y encuentra el video pero no da opcioon a Guardar...solo guardar imagen como.....
                                                   Saludos

**Comment by aabilio** [comment]
A mi sí me funciona. Tanto T5 como MiTele. Puede que lo estés haciendo mal, no hay que hacer clic sobre la imagen, sino sobre el enlace. Por si acaso, mira esta parte del vídeo de ayuda: https://www.youtube.com/watch?v=1_y9MXiHhis#t=49

Saludos.

**Comment by lusoma** [comment]
He pecado de pardillo,no me aparecia el  titulo,a partir del 1. por tener un script bloqueado.
          Gracias y saludos.
PD- Al registrarme aqui me he liado en el paso3. Me sale "Add owners to the usopersonal organization"  y termino apareciendo en algo como "añadir repositorios". Supongo que sera por poner como organizacion "usopersonal" cuando no soy organizacion si no simple usuario.

**Comment by aabilio** [comment]
Bueno, pues parece que solucionado entonces ;)
