### ISSUE TITLE
Api problema (atresplayer)

### ISSUE THREAD

**Issue by peter55** [aabilio/PyDownTV2#104]
Hola.

Para sacar enlaces de atresplayer por la api hay problemas con algunos de ellos no se si por tema de espacios o por la ñ. Por ejemplo en los de Arguiñano.
Ejemplo:
www.pydowntv.com/api?url=http://www.atresplayer.com/television/programas/karlos-argui%C3%B1ano-en-tu-cocina/temporada-1/capitulo-109-cardo-salsa-nueces-huevos-codorniz_2014021000161.html

Gracias. Saludos.

**Comment by aabilio** [comment]
Evidentemente tengo que arreglar esos fallos, pero cuando sea así, dale formato a la url tipo %encode, por ejemplo: http://www.pydowntv.com/api/http%3A//www.atresplayer.com/television/programas/karlos-argui%25C3%25B1ano-en-tu-cocina/temporada-1/capitulo-160-crema-esprragos-verde-galletas-queso_2014042500160.html

Por cierto, la API para atresplayer ahora mismo la no da la url del vídeo final, sino que da un endpoint de la API interna de atresplayer a la que hay que acceder logueado (en atrsplayer), y en donde se encuentra la url final del vídeo.

Saludos.
