### ISSUE TITLE
No puedo descargar los enlaces de Mitele para rtmpdump

### ISSUE THREAD

**Issue by paloma66** [aabilio/PyDownTV2#106]
Hola intento descargar el enlace rtmpdump :

http://www.mitele.es/telenovelas/mentir-para-vivir/temporada-1/capitulo-2/

```
rtmpdump -r "rtmpe://cp272476.edgefcs.net/ondemand/" -y "mp4:1/rtmpe/geo/serie/mentirparavivir/t1/c2_2243e364.mp4?auth=daEb3b.a2b9aWaSd8dsakdudIcJctcDapcM-btaqMF-i-AsEnyo_BvlHDn&aifp=1234&slist=1/rtmpe/geo/serie/mentirparavivir/t1/c2_2243e364.mp4" -a "ondemand?auth=daEb3b.a2b9aWaSd8dsakdudIcJctcDapcM-btaqMF-i-AsEnyo_BvlHDn&aifp=1234&slist=1/rtmpe/geo/serie/mentirparavivir/t1/c2_2243e364.mp4" -u "auth=daEb3b.a2b9aWaSd8dsakdudIcJctcDapcM-btaqMF-i-AsEnyo_BvlHDn&aifp=1234&slist=1/rtmpe/geo/serie/mentirparavivir/t1/c2_2243e364.mp4" -s "http://static1.tele-cinco.net/comun/swf/playerMitele.swf" -o "Capitulo_2-Ines_se_suicida_-Ines_se_suicida--Mentir_para_vivir-Temporada_1.mp4"
```

pero no se puede , escribe ERROR : rtmp server sent error
                                            ERROR: rtmp server requested close

sera problema mio o temporal del servidor o de Mitele , no se !!!???!! podrian aclararme  por favor , muchisssssimas gracias por su atencion...

**Comment by aabilio** [comment]
El problema puede ser la "tardanza" en ejecutar el comando.. ya que tiene un tiempo de vida muy corto. Prueba a hacerlo lo más rápido posible (a mi el comando que devuelve pydowntv me ha funcionado).
Saludos.

**Comment by denobisipsis** [comment]
Asegurate de tener la ultima version del rtmpdump y vuelve a obtener el
link. Caduca rapido

**Comment by ismanastic** [comment]
He seguido los pasos del tutorial para rtmpdump y sigo sin enterarme de cómo se hace...
Me he descargado el .exe del archivo, lo he pegado en la carpeta System32, abro la consola de Windows y?? Ahí qué se le pega?
Por ejemplo:
Comandos para rtmpdump:

rtmpdump -r "rtmpe://cp272476.edgefcs.net/ondemand/" -y "mp4:1/rtmpe/geo/programa/hayunacosaquetequierodecir/t3/c58_89e34d6c.mp4?auth=daEc1dHb5dsaxbdbtaVbUbsb_bTaadQclda-btaHlX-i-yuFoBq_BqmGBw&aifp=1234&slist=1/rtmpe/geo/programa/hayunacosaquetequierodecir/t3/c58_89e34d6c.mp4" -a "ondemand?auth=daEc1dHb5dsaxbdbtaVbUbsb_bTaadQclda-btaHlX-i-yuFoBq_BqmGBw&aifp=1234&slist=1/rtmpe/geo/programa/hayunacosaquetequierodecir/t3/c58_89e34d6c.mp4" -u "auth=daEc1dHb5dsaxbdbtaVbUbsb_bTaadQclda-btaHlX-i-yuFoBq_BqmGBw&aifp=1234&slist=1/rtmpe/geo/programa/hayunacosaquetequierodecir/t3/c58_89e34d6c.mp4" -s "http://static1.tele-cinco.net/comun/swf/playerMitele.swf" -o "Programa_58_-David_Hasselhoff_invitado_estrella_-David_Hasselhoff_invitado_estrella--Hay_una_cosa_que_te_quiero_decir-Temporada_3.mp4"

Qué debo copiar en la consola de eso? He probado diferentes cosas y no me sale más que error y error ^^ 
Y por cierto, he copiado eso, pero si le doy a abrir, se cierra de nuevo. Se hace con la consola de Windows no? Lo que no pillo es por qué es necesario copiar eso :S 
Agradecería vuestra ayuda. GRACIAS!

PD: y perdón por ser tan cortito, pero realmente no sé hacerlo yo solo

**Comment by stamaty** [comment]
Yo tampoco puedo. Creo que tengo la última versión de rtmpdump 2.4 y he intentado copiar el link y ejecutarlo lo más rápido posible. No hay manera, me da el mismo error que a Paloma66. No se que hago mal...

**Comment by aabilio** [comment]
Mañana habrá un intento de solución. A ver qué tal.. (o esta noche)

**Comment by paloma66** [comment]
Muchas gracias por intertarlo y por todo el interes

**Comment by atomblu** [comment]
De verdad que no consigo entender porque mitele pone siete telenovelas nuevas que no se pueden ver online desde su página web. He intentado verlas directamente sin tener que descargarlas y no se puede! Son unos chapuceros. Si intentas verlo desde la web de mitele primero que está continuamente cargando con el circulo dando vueltas en el medio. Tienes que esperar bastante tiempo hasta que continua, y después de estar cargando te meten dos o tres anuncios, y luego continua la novela y si tienes suerte consigues verla a lo mejor un minuto, y se vuelve a parar, a cargar, y cuando por fin continua te meten mas anuncios. Como se puede creer esta gente de mitele que se puede ver un video de esa forma? Para que los ponen entonces? Es ridículo! Tiene uno que descargarlo si lo quiere ver y tampoco se puede! Estoy harta de verdad!

**Comment by denobisipsis** [comment]
Si aabilio me permite, estoy intentando comprender porqué al copiar el link y ejecutarlo no va, ya que en mi servidor se descarga perfectamente y con el programa atres también. Si estáis interesados verdaderamente podéis utilizarlo:

http://www58.zippyshare.com/v/66894968/file.html

**Comment by atomblu** [comment]
Por favor, si es posible, que el arreglo no tenga que ver con esto de rtmp por que en mi sistema por lo menos, (windows 8.1) no me acepta el comando. Dice una y otra vez que el comando rtmpdump es invalido. 

Gracias.

**Comment by atomblu** [comment]
Gracias Denobis por recordarme lo de atres para descargar.  Voy a intentarlo pero se me olvido la contraseña y no pueda loguear. Qué hago?

Gracias.

Dolores

**Comment by denobisipsis** [comment]
No hace falta ninguna contraseña, a no ser que sea para atresmedia

**Comment by atomblu** [comment]
Para atresmedia downloader hay un login y un password.

On Friday, February 21, 2014 12:11:24 PM, denobis notifications@github.com wrote:

No hace falta ninguna contraseña, a no ser que sea para atresmedia

**Comment by atomblu** [comment]
Si abres la pagina que te mando veras arriba a la izquierda el login y
password.  Al no ser que esté completamente equivocada y esto no sea a lo
que te refieres para descargar estas telenovelas de mitele. A mí no me funciona
nada. Y como ya he dicho no puedo verlo online tampoco.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Para atresmedia downloader hay un login y un password.

On Friday, February 21, 2014 12:11:24 PM, denobis notifications@github.com wrote:

No hace falta ninguna contraseña, a no ser que sea para atresmedia

**Comment by denobisipsis** [comment]
Para mitele no es necesario

mira:

http://postimg.org/image/pddu43khl/

**Comment by atomblu** [comment]
Lo intentare. Hasta ahora no he tenido suerte.

On Friday, February 21, 2014 12:52:28 PM, denobis notifications@github.com wrote:

Para mitele no es necesario
mira:
http://postimg.org/image/pddu43khl/

**Comment by atomblu** [comment]
No me
funciona.  En la pagina que adjunto veras
como se queda. Siempre indica que esta descargando 1 y  los números están a cero siempre.  Y nunca empieza a descargar.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Lo intentare. Hasta ahora no he tenido suerte.

On Friday, February 21, 2014 12:52:28 PM, denobis notifications@github.com wrote:

Para mitele no es necesario
mira:
http://postimg.org/image/pddu43khl/

**Comment by atomblu** [comment]
Cuando
abro el atresplayer siempre indica 6 descargos en cola. No lo entiendo porque
aun no he pegado el url. Termina estos 6 descargos y luego se para. Y cuando yo pego el url del
video no descarga nada más.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

No me
funciona.  En la pagina que adjunto veras
como se queda. Siempre indica que esta descargando 1 y  los números están a cero siempre.  Y nunca empieza a descargar.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Lo intentare. Hasta ahora no he tenido suerte.

On Friday, February 21, 2014 12:52:28 PM, denobis notifications@github.com wrote:

Para mitele no es necesario
mira:
http://postimg.org/image/pddu43khl/

**Comment by atomblu** [comment]
Perdona, vuelvo a mandar la pagina.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Cuando
abro el atresplayer siempre indica 6 descargos en cola. No lo entiendo porque
aun no he pegado el url. Termina estos 6 descargos y luego se para. Y cuando yo pego el url del
video no descarga nada más.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

No me
funciona.  En la pagina que adjunto veras
como se queda. Siempre indica que esta descargando 1 y  los números están a cero siempre.  Y nunca empieza a descargar.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Lo intentare. Hasta ahora no he tenido suerte.

On Friday, February 21, 2014 12:52:28 PM, denobis notifications@github.com wrote:

Para mitele no es necesario
mira:
http://postimg.org/image/pddu43khl/

**Comment by atomblu** [comment]
Creo que por fin lo he solucionada. Si no funciona, lo dejo. Perdona las molestias.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Perdona, vuelvo a mandar la pagina.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Cuando
abro el atresplayer siempre indica 6 descargos en cola. No lo entiendo porque
aun no he pegado el url. Termina estos 6 descargos y luego se para. Y cuando yo pego el url del
video no descarga nada más.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

No me
funciona.  En la pagina que adjunto veras
como se queda. Siempre indica que esta descargando 1 y  los números están a cero siempre.  Y nunca empieza a descargar.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Lo intentare. Hasta ahora no he tenido suerte.

On Friday, February 21, 2014 12:52:28 PM, denobis notifications@github.com wrote:

Para mitele no es necesario
mira:
http://postimg.org/image/pddu43khl/

**Comment by atomblu** [comment]
Por fin funciona! Con atresplayer downloader. Muchisimas gracias a todos.

**Comment by aabilio** [comment]
He añadido una pequeña ayuda más.
Ejemplo: http://web.pydowntv.com/?url=http%3A//www.mitele.es/telenovelas/la-tempestad/temporada-1/capitulo-10/
FAQ: http://www.pydowntv.com/ayuda#DescargarRtmpEasy

**Comment by stamaty** [comment]
He utilizado las ayudas para descargar rtmpdump de la página. Lo primero decir que FUNCIONA!
Luego explico que he hecho varias descargas:en todas el archivo generado no tiene extensión, le he añadido el .mp4 y  perfecto. Como la descarga se añade automáticamente, no toco nada de donde dice comando: y nombre:. Quizá tendria que poner ahí el nombre que quiero del archivo, pero no se muy bien como, todo va automático.  En una descarga le he dado al play antes de copiar el link y la descarga me ha dado error.
La calidad es regular, pero es la que mitele ofrece en linea.
Gracias por todo.

**Comment by aabilio** [comment]
Tanto easy rtmpdump como rtmp downloader desde pydowntv no tiene soporte
para cambiar el nombre de archivo resultante. Lo tendrá para los dos..

El sábado, 22 de febrero de 2014, stamaty notifications@github.com
escribió:

> He utilizado las ayudas para descargar rtmpdump de la página. Lo primero
> decir que FUNCIONA!
> Luego explico que he hecho varias descargas:en todas el archivo generado
> no tiene extensión, le he añadido el .mp4 y perfecto. Como la descarga se
> añade automáticamente, no toco nada de donde dice comando: y nombre:. Quizá
> tendria que poner ahí el nombre que quiero del archivo, pero no se muy bien
> como, todo va automático. En una descarga le he dado al play antes de
> copiar el link y la descarga me ha dado error.
> La calidad es regular, pero es la que mitele ofrece en linea.
> Gracias por todo.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/aabilio/PyDownTV2/issues/106#issuecomment-35805884
> .

## 

aabilio - http://web.pydowntv.com
GPG id 81D115C4 Abilio Almeida Eiroa (aabilio)
SIP: aabilio@ekiga.net Skype: @a_abilio

**Comment by atomblu** [comment]
Imposible descargar este capitulo:

http://www.mitele.es/telenovelas/la-tempestad/temporada-1/capitulo-1/

Se queda en cola sin descargar.

Muchas gracias.

On Saturday, February 22, 2014 1:03:53 PM, Abilio Almeida (aabilio) notifications@github.com wrote:

Tanto easy rtmpdump como rtmp downloader desde pydowntv no tiene soporte 
para cambiar el nombre de archivo resultante. Lo tendrá para los dos.. 

El sábado, 22 de febrero de 2014, stamaty notifications@github.com 
escribió: 

> He utilizado las ayudas para descargar rtmpdump de la página. Lo primero 
> decir que FUNCIONA! 
> Luego explico que he hecho varias descargas:en todas el archivo generado 
> no tiene extensión, le he añadido el .mp4 y perfecto. Como la descarga se 
> añade automáticamente, no toco nada de donde dice comando: y nombre:. Quizá 
> tendria que poner ahí el nombre que quiero del archivo, pero no se muy bien 
> como, todo va automático. En una descarga le he dado al play antes de 
> copiar el link y la descarga me ha dado error. 
> La calidad es regular, pero es la que mitele ofrece en linea. 
> Gracias por todo. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/aabilio/PyDownTV2/issues/106#issuecomment-35805884 
> . 

## 

aabilio - http://web.pydowntv.com 
GPG id 81D115C4 Abilio Almeida Eiroa (aabilio) 
SIP: aabilio@ekiga.net Skype: @a_abilio

**Comment by denobisipsis** [comment]
Atomblue, si ocurre eso para la descarga (menú funciones de cola) y vuelve a buscar. A veces pasa, pero al final se descarga.

**Comment by atomblu** [comment]
Gracias. Lo seguire intentando.

On Sunday, February 23, 2014 11:09:28 AM, denobis notifications@github.com wrote:

Atomblue, si ocurre eso para la descarga (menú funciones de cola) y vuelve a buscar. A veces pasa, pero al final se descarga.

**Comment by atomblu** [comment]
Que puedo hacer cuando se para por ejemplo en 35% de descargo y de ahi no pasa.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Gracias. Lo seguire intentando.

On Sunday, February 23, 2014 11:09:28 AM, denobis notifications@github.com wrote:

Atomblue, si ocurre eso para la descarga (menú funciones de cola) y vuelve a buscar. A veces pasa, pero al final se descarga.

**Comment by denobisipsis** [comment]
Esperar, está programado para parar de descargar sólo cuando se complete, a no ser que tú lo pares manualmente. Por experiencia te digo que los rtmp pueden pararse y tras un tiempo continúar, eso significa que se ha cortado la conexión, pero el programa la recupera las veces necesarias.

**Comment by atomblu** [comment]
Me he encontrado con un problema nuevo.  He notado ya dos veces que termina de descargar un capitulo y cuando abro la carpeta no esta el video. Como puede suceder eso? Ha sido despues de cambiar a la ultima version de atres downloader.

On Sunday, February 23, 2014 11:47:31 AM, denobis notifications@github.com wrote:

Esperar, está programado para parar de descargar sólo cuando se complete, a no ser que tú lo pares manualmente. Por experiencia te digo que los rtmp pueden pararse y tras un tiempo continúar, eso significa que se ha cortado la conexión, pero el programa la recupera las veces necesarias.

**Comment by atomblu** [comment]
Ha dejado de funcionar.  He vuelto a descargar otro capitulo y la carpeta de descargos esta completamente vacia.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Me he encontrado con un problema nuevo.  He notado ya dos veces que termina de descargar un capitulo y cuando abro la carpeta no esta el video. Como puede suceder eso? Ha sido despues de cambiar a la ultima version de atres downloader.

On Sunday, February 23, 2014 11:47:31 AM, denobis notifications@github.com wrote:

Esperar, está programado para parar de descargar sólo cuando se complete, a no ser que tú lo pares manualmente. Por experiencia te digo que los rtmp pueden pararse y tras un tiempo continúar, eso significa que se ha cortado la conexión, pero el programa la recupera las veces necesarias.

**Comment by atomblu** [comment]
He vuelto a descargar de nuevo atresdownloader 14.1 para probar desde un principio y no funciona. Cuando abro la carpeta gris, al lado del triangulo naranja, solo se ve una carpeta que pone IMG. No hay nada mas. No se que ha pasado.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Ha dejado de funcionar.  He vuelto a descargar otro capitulo y la carpeta de descargos esta completamente vacia.

On , DOLORES JIMENEZ mdjn@rogers.com wrote:

Me he encontrado con un problema nuevo.  He notado ya dos veces que termina de descargar un capitulo y cuando abro la carpeta no esta el video. Como puede suceder eso? Ha sido despues de cambiar a la ultima version de atres downloader.

On Sunday, February 23, 2014 11:47:31 AM, denobis notifications@github.com wrote:

Esperar, está programado para parar de descargar sólo cuando se complete, a no ser que tú lo pares manualmente. Por experiencia te digo que los rtmp pueden pararse y tras un tiempo continúar, eso significa que se ha cortado la conexión, pero el programa la recupera las veces necesarias.

**Comment by ismanastic** [comment]
He probado el nuevo A3 Multi Downloader y al menos ya me encuentra el vídeo rtmpdump, pero ahora surge el problema de que se queda parpadeando y no descarga nada y si le das, te dice que ya está en proceso. Además me he fijado que te da una descarga gigantesca: normalmente esos programas pesan entre 1'9 y 2 gigas, aquí me da uno de 6'1 gigas, lo que es una salvajada.
Es normal?

**Comment by denobisipsis** [comment]
Dime con qué video

**Comment by ismanastic** [comment]
http://www.mitele.es/programas-tv/hay-una-cosa-que-te-quiero-decir/temporada-3/programa-58/

Lo que he hecho ahora es leer que @aabilio puso un tutorial con otro programa alternativo, que abre una página y tal. Parece que ese funciona, ya te diré, pero va para largo porque es un programa de 4 horas. Aun así, te agradecería que miraras lo del A3 Multi-Downloader :)

**Comment by denobisipsis** [comment]
Lo del tamaño es una estimación en función del bitrate y la duración, así que es orientativo aunque en la mayoría de ocasiones funciona. Si el rtmp se queda a cero sin avanzar lo que tienes que hacer es cancelar y volver a buscar.

**Comment by ismanastic** [comment]
No sé qué diantres he hecho, pero ahora no me funciona lo otro pero sí el Multi-Downloader :S 
Ahora ni me carga el pydown, a saber qué le pasa. Al menos me descarga ya, pero esos 6'21 gigas me va a tardar una eternidad ^^ y para riperarlo ni te digo puajjj.
Tienen relación un programa con otro? Porque al ir a cerrar lo que tuve abierto del A3 Multi-D es cuando me ha cancelado la otra descarga y ahora no me permite hacer nada

**Comment by denobisipsis** [comment]
Como te digo, a veces falla la primera vez y no descarga, pero si pruebas más veces te lo saca. No tienen relación los programas, es mejor que los corras en tiempos distintos cuando se trate de rtmp. Sobre los 6 GB la información que obtengo es que dura 239 minutos a un bitrate combinado de 1800. Eso son casi 4 horas a un alto bitrate, por lo que es factible.

**Comment by ismanastic** [comment]
Pero en pydown siempre me da unos 1'9-2 gigas, puedes comprobarlo en cualquier programa.
Lo más curioso es que de las 3 temporadas solo ese programa me ha dado ese quebradero de cabeza...y que conste que no miro el programa xD es más, ni me interesa, pero suelo descargarlo todo

**Comment by denobisipsis** [comment]
Ya está arreglado, efectivamente son dos gigas, con un bitrate real de unos
1200.

**Comment by ismanastic** [comment]
Lo he descargado. Se desincroniza, pero menos es nada. Es leve el desfase, pero se "nota",,,y se queda como a medias, porque al descargar se paraliza en "Faltan 2 segundos" y de ahí no pasa. Lo he tenido casi 1 hora así y nada, lo he cancelado y ya, total, serán 1 o 2 segundos del programa y dudo que sea ese el motivo de la desincro.
Gracias!
Entre @denobis y @aabilio nos van dando mil y una soluciones a nuestros problemas. Sois unos cracks!!

**Comment by stamaty** [comment]
Sigo utilizando rtmp downloader desde pydowntv y va como la seda. Perfecto, ni un solo problema!
