### ISSUE TITLE
RTMP DOWNLOAD NO FUNCIONA

### ISSUE THREAD

**Issue by atomblu** [aabilio/PyDownTV2#108]
Llev dos dias probando y no funciona. Imediatamente pone fallo y fallo y fallo. No  importa que video sea falla una y otra vez.

**Comment by aabilio** [comment]
¿te sigue fallando?

**Comment by atomblu** [comment]
Hola. No, funciona de maravilla ahora.   Perdona si no conteste es que tuve una pequeña
emergencia estos últimos días.  Muchas
gracias por preguntar y por todo el trabajo que haces. 
Saludos
Dolores.

On Monday, March 10, 2014 7:46:42 AM, Abilio Almeida (aabilio) notifications@github.com wrote:

te sigue fallando?

**Comment by atomblu** [comment]
Hoy
dejo de funcionar RTMP DOWNLOADER VO 2B.  Se abre la ventanita
negra y se queda diciendo Espere por favor y nunca empieza a descargar el
contenido.  En la pagina que se abre en
el navegador da un fallo inmediatamente. Esto ocurrió una vez ya hace tiempo.
No sé por qué ocurre de repente.
 
Gracias.

**Comment by forestrf** [comment]
Qué vídeo provoca el fallo?

**Comment by atomblu** [comment]
Incluyo un pdf donde se ve la ventanilla negra que se queda asi con "espere por favo", la ventana de rtmp que indica el fallo, y pydowntv con la novela. Me da fallo en todas las telenovelas de mitele.es. Ocurrio por primera vez ayer.

Gracias.
On Saturday, April 12, 2014 7:41:26 AM, Andrés notifications@github.com wrote:

Qué vídeo provoca el fallo?
