### ISSUE TITLE
Paydowntv no funciona con ATRESPLAYER

### ISSUE THREAD

**Issue by Llongueraitis** [aabilio/PyDownTV2#115]
He copiado la URL correctamente:
http://www.atresplayer.com/television/programas/tu-cara-me-suena/temporada-1/tu-cara-me-suena_2011122300221.html
Y cada vez me da error, he probado con chrome y firefox y no hay nada que hacer.

Estan seguros que funciona?
![error atresplayer](https://f.cloud.github.com/assets/7052733/2506562/46e37ea6-b3a9-11e3-97da-a8201c007276.jpg)

**Comment by aabilio** [comment]
El vídeo al que intentas acceder es de pago y pydowntv no soporta este tipo de vídeos. Saludos.

**Comment by Llongueraitis** [comment]
Muchas gracias por la información.

Sabes alguna manera de hacerlo?, porque mi hija pequeña me tiene loco con este programa y quisiera bajarle la 1era y 2da temporada.

En series yonkis están casi todos los episodios pero se ven fatal y están desincronizados muchos de ellos.

Por torrent sólo están los últimos en mp4 que se ven muy bien.

Gracias por tu ayuda

De: Abilio Almeida (aabilio) [mailto:notifications@github.com] 
Enviado el: martes, 25 de marzo de 2014 0:13
Para: aabilio/PyDownTV2
CC: Llongueraitis
Asunto: Re: [PyDownTV2] Paydowntv no funciona con ATRESPLAYER (#115)

El vídeo al que intentas acceder es de pago y pydowntv no soporta este tipo de vídeos. Saludos.
