### ISSUE TITLE
Vídeos descargados en Linux con el flag ejecutable

### ISSUE THREAD

**Issue by simonbcn** [aabilio/PyDownTV2#117]
Ubuntu 13.10 64 bits
PyDownTV 0.1.0-ALPHA

Usando el script me he bajado varios vídeos de diferentes TVs y todos se bajan con el flag "x" (ejecutable) activado. ¿Por qué? Esto no debería ser así y es un fallo de seguridad.

**Comment by aabilio** [comment]
Tienes razón, no me había dado cuenta ;)
El problema está al crear el archivo con os.open (aquí: https://github.com/aabilio/PyDownTV2/blob/master/Script/pyaxel/pyaxel.py#L342).
Debería ser: out_fd = os.open(output_file+".part", os.O_CREAT | os.O_WRONLY, 0600) para que el archivo solo quedara con permisos de lectura y escritura.

Lo tengo cambiado, haré push dentro de poco.
Saludos.
