### ISSUE TITLE
rtmp downloader

### ISSUE THREAD

**Issue by atomblu** [aabilio/PyDownTV2#119]
Lleva todo el dia dando fallos. No se que pasa.

**Comment by aabilio** [comment]
Forest va sacando nuevas versión del programa. Puedes verlas aquí y probar otras si una no te funciona: https://github.com/forestrf/RTMP-Downloader/releases

Saludos!

**Comment by atomblu** [comment]
Muchas gracias.
On Monday, April 28, 2014 6:02:11 AM, Abilio Almeida (aabilio) notifications@github.com wrote:

Forest va sacando nuevas versión del programa. Puedes verlas aquí y probar otras si una no te funciona: https://github.com/forestrf/RTMP-Downloader/releases
Saludos!

**Comment by atomblu** [comment]
He probado la version nueva y solo funciona de vez en cuando. Tengo que estar todo el dia probando hasta conseguirlo.  No funciona como debia de funcionar.
On Monday, April 28, 2014 3:20:51 PM, DOLORES JIMENEZ mdjn@rogers.com wrote:

Muchas gracias.
On Monday, April 28, 2014 6:02:11 AM, Abilio Almeida (aabilio) notifications@github.com wrote:

Forest va sacando nuevas versión del programa. Puedes verlas aquí y probar otras si una no te funciona: https://github.com/forestrf/RTMP-Downloader/releases
Saludos!
