### ISSUE TITLE
problemas reproducción videos tvg con verión web pydowntv

### ISSUE THREAD

**Issue by vitorfontam** [aabilio/PyDownTV2#12]
He descargado varios vídeos, variados, de la Televisión de Galicia usando Pydowntv. No he tenido ningún problema, los descarga perfectamente. El problema viene a la hora de reproducirlos: cada 20-30 segundos la reprodución se interrumpe volviendo hacia atrás repitiendo los anteriores 5-10 segundos. Pasa con todos los vídeso que he descargado sin excepción y no encuentro la solución. Mi sestema operativo es Ubuntu 12.04 y he probado con varios reproductores.
Muchas gracias por su atención.

**Comment by aabilio** [comment]
El problema está a la hora de descargarlo.
Prueba a poner el rtmpdump en modo live añadiendo el flag "-v" al comando proporcionado por PyDownTV a ver qué pasa ;)

**Comment by vitorfontam** [comment]
Funciona! No conocía ese truco, que me será de mucha ayuda.
Muchísimas gracias.

**Comment by aabilio** [comment]
Ya son algunas personas que me comentan que les va mejor con el "-v" así que lo pondré directamente en el comando que proporcione PyDownTV.
Cierro Issue.
