### ISSUE TITLE
Videos en HD

### ISSUE THREAD

**Issue by Salvat0res** [aabilio/PyDownTV2#120]
¿Existe la posiblidad de descargar en calidad HD?

**Comment by aabilio** [comment]
PyDownTV no tiene ninguna manera de descargar vídeos de otra forma que no sea la que se publica (para algunos vídeos se dan varias opciones de calidad).
Si lo que quieres son vídeo en HD de atresplayer, y tienes Windows puedes usar este software de Denobis: http://www.mediafire.com/download/z4jujjg5975udck/a3toMP4v15.exe

Saludos.
