### ISSUE TITLE
Falla al obtener ciertos enlaces de EITB

### ISSUE THREAD

**Issue by bdovaz** [aabilio/PyDownTV2#121]
Me he fijado que en la web pone que EITB es por RTMP pero ahora es por HTTP.

Mi problema es que con contenidos nuevos parece que funciona bien al obtener los enlaces pero no con los antiguos (pone "File not found."").

Ejemplo correcto:

http://www.eitb.tv/es/video/kontrako-eztarria-lo-ultimo/676435921001/3525645190001/kontrako-eztarria--2014-0501-/

Ejemplo incorrecto:

http://www.eitb.tv/es/video/el-conquistour--2012/1663668850001/1694306258001/bergara/

**Comment by bdovaz** [comment]
¿Lo puedes mirar por favor?

Gracias!

**Comment by aabilio** [comment]
En cuanto pueda lo miro

**Comment by aabilio** [comment]
Los enlaces que me pasas, ahora mismo no puedo acceder a ellos a través del navegador. Es decir, me carga la página sin error, pero luego no parece haber vídeo en ella. ¿Puedes comprobar esto por favor?

**Comment by bdovaz** [comment]
En los 2 casos funciona (Chrome 35) lo que pasa que va sobre flash con lo que si tienes alguna extensión que lo bloquee no te va a cargar.

De todas maneras da igual, mira cualquier otro programa anterior a 2014 y pasará lo mismo.

**Comment by aabilio** [comment]
Parece que ya van bien ;)
