### ISSUE TITLE
No funcionan los enlaces de mitele

### ISSUE THREAD

**Issue by bdominguez** [aabilio/PyDownTV2#123]
Pues eso, desde esta noche no funcionan los enlaces de mitele ni desde la api ni desde la web.

**Comment by aabilio** [comment]
Ha sido un error en una migración. Dentro de poco tendría que empezar a funcionar con normalidad otra vez.
Gracias por reportar.
Saludos.

**Comment by aabilio** [comment]
Parece que todo ya empieza a funcionar con normalidad.

**Comment by bdovaz** [comment]
Gracias!
