### ISSUE TITLE
No funcionan los enlaces de Telemadrid

### ISSUE THREAD

**Issue by bdovaz** [aabilio/PyDownTV2#124]
Estoy probando los enlaces y no funcionan. Ejemplo reciente:

http://www.pydowntv.com/api/http://www.telemadrid.es/programas/hora-deportiva/hora-deportiva-08052014

¿Podéis mirarlo?

Gracias!!

**Comment by aabilio** [comment]
ok. Gracias por reportar.

**Comment by aabilio** [comment]
Ya debería estar funcionando con normalidad otra vez. Échale un ojo.

API: http://www.pydowntv.com/api/http://www.telemadrid.es/programas/hora-deportiva/hora-deportiva-08052014

``` json
{"videos": [{"url_video": ["http://telemadrid-f.akamaihd.net/hd/104403117001/201405/104403117001_3546825808001_26861938-2f58-4249-9fee-d692b7fde521.mp4?v=&fp=&r=&g="], "rtmpd_cmd": null, "partes": 1, "tipo": "http", "mensaje": null, "menco_cmd": null, "url_publi": null, "url_img": "http://www.telemadrid.es/sites/default/files/images/atleticomadrid_0805.jpg", "otros": null, "filename": ["Hora_Deportiva_08.05.2014.mp4"]}], "descs": ["Hora Deportiva 08.05.2014"], "titulos": ["Hora Deportiva 08.05.2014"], "exito": true, "mensaje": "URL obtenido correctamente", "num_videos": 1}
```

Web: http://www.pydowntv.com/?url=http://www.telemadrid.es/programas/hora-deportiva/hora-deportiva-08052014

Saludos.

**Comment by bdovaz** [comment]
Sí que funciona pero si abro directamente la url en Google Chrome no me carga el reproductor de HTML5 (el de serie) para ver el MP4 (como siempre pasa) sino que me intenta cargar el plugin de vlc (que tengo instalado). ¿Por qué puede ser?

Es que uso la API para enviar vídeos a Chromecast y si no devuelve el vídeo no me va a funcionar.

Gracias!

**Comment by aabilio** [comment]
Supongo que será por el tipo de de vídeo (el encoding). Pero de todas maneras es un vídeo.. ¿no te lo reproduce el chromecast?

**Comment by bdovaz** [comment]
No parece, he hecho una prueba rápida con este servicio:

http://movies.foamsnet.com/url/

Y lo que hace es intentar cargarlo en Chromecast pero vuelve al menu (eso suele pasar cuando no puede reproducirlo).

Que de hecho ahí aparecen los codecs y formatos que soporta.

**Comment by aabilio** [comment]
Pues no sé, un vídeo es.. el GET devuelve:

```
Cache-Control:max-age=0, no-cache
Connection:keep-alive
Content-Length:2147483647
Content-Type:video/x-flv
Date:Thu, 08 May 2014 16:58:29 GMT
Expires:Thu, 08 May 2014 16:58:29 GMT
Mime-Version:1.0
Pragma:no-cache
Server:AkamaiGHost
```

**Comment by bdovaz** [comment]
Igual es por la cabecera? "video/x-flv"

Aunque el formato sea MP4 devuelve en la cabecera otro tipo de contenido.

**Comment by aabilio** [comment]
Esto es lo que devuelve la API de brightcove:

``` python
{'FLVFullCodec': 3,
 'FLVFullLengthStreamed': True,
 'FLVFullLengthURL': u'http://telemadrid-f.akamaihd.net/hd/104403117001/201405/104403117001_3546815621001_26861938-2f58-4249-9fee-d692b7fde521.mp4',
 'FLVFullSize': 55932148.0,
 'FLVPreBumperControllerType': 0,
 'FLVPreBumperStreamed': False,
 'FLVPreBumperURL': None,
 'FLVPreviewCodec': 0,
 'FLVPreviewSize': 0.0,
 'FLVPreviewStreamed': False,
 'FLVPreviewURL': None,
 'HDSRenditions': None,
 'IOSRenditions': [{'audioOnly': False,
   'defaultURL': u'http://c.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=3546806666001',
   'encodingRate': 264000,
   'frameHeight': 268,
   'frameWidth': 480,
   'mediaDeliveryType': 2,
   'size': 32640727.0,
   'videoCodec': u'H264',
   'videoContainer': 2}],
 'SWFVerificationRequired': False,
 'WMVFullAssetId': None,
 'WMVFullLengthURL': None,
 'adCategories': None,
 'adKeys': None,
 'allowViralSyndication': True,
 'allowedCountries': [],
 'awards': None,
 'captions': None,
 'categories': [],
 'color': True,
 'controllerType': 5,
 'creationDate': datetime.datetime(2014, 5, 8, 15, 7, 53, 617000),
 'cuePoints': None,
 'customFieldValues': None,
 'customFields': None,
 'dateFiltered': False,
 'displayName': u'Hora Deportiva 08.05.2014',
 'drmMetadataURL': None,
 'economics': 1,
 'encodingRate': 457195,
 'endDate': None,
 'excludeListedCountries': False,
 'filterEndDate': None,
 'filterStartDate': None,
 'forceAds': False,
 'geoRestricted': False,
 'hdsManifestUrl': None,
 'id': 3546789252001.0,
 'isSubmitted': False,
 'language': u'SPANISH',
 'length': 957754.0,
 'lineupId': None,
 'linkText': None,
 'linkURL': None,
 'logoOverlay': None,
 'longDescription': u'Hora Deportiva 08.05.2014',
 'monthlyAmount': None,
 'numberOfPlays': 0.0,
 'previewLength': 0.0,
 'publishedDate': datetime.datetime(2014, 5, 8, 15, 7, 53, 617000),
 'publisherId': 104403117001.0,
 'publisherName': u'Telemadrid',
 'purchaseAmount': None,
 'ratingEnum': None,
 'referenceId': u'26861938-2f58-4249-9fee-d692b7fde521',
 'renditions': [{'audioOnly': False,
   'defaultURL': u'http://telemadrid-f.akamaihd.net/hd/104403117001/201405/104403117001_3546825808001_26861938-2f58-4249-9fee-d692b7fde521.mp4',
   'encodingRate': 908616,
   'frameHeight': 268,
   'frameWidth': 480,
   'mediaDeliveryType': 0,
   'size': 110486787.0,
   'videoCodec': u'H264',
   'videoContainer': 1},
  {'audioOnly': False,
   'defaultURL': u'http://telemadrid-f.akamaihd.net/hd/104403117001/201405/104403117001_3546815621001_26861938-2f58-4249-9fee-d692b7fde521.mp4',
   'encodingRate': 457195,
   'frameHeight': 268,
   'frameWidth': 480,
   'mediaDeliveryType': 0,
   'size': 55932148.0,
   'videoCodec': u'H264',
   'videoContainer': 1},
  {'audioOnly': False,
   'defaultURL': u'http://telemadrid-f.akamaihd.net/hd/104403117001/201405/104403117001_3546807486001_26861938-2f58-4249-9fee-d692b7fde521.mp4',
   'encodingRate': 257195,
   'frameHeight': 268,
   'frameWidth': 480,
   'mediaDeliveryType': 0,
   'size': 31799693.0,
   'videoCodec': u'H264',
   'videoContainer': 1}],
 'rentalAmount': None,
 'rentalPeriod': None,
 'sharedBy': None,
 'sharedByExternalAcct': False,
 'sharedSourceId': None,
 'sharedToExternalAcct': False,
 'shortDescription': u'Hora Deportiva 08.05.2014',
 'startDate': None,
 'submitted': False,
 'tags': [{'image': None, 'name': u'telemadrid'},
  {'image': None, 'name': u'Hora deportiva'},
  {'image': None, 'name': u'programa deportes'}],
 'thumbnailURL': u'http://www.telemadrid.es/sites/default/files/images/atleticomadrid_0805.jpg',
 'version': None,
 'videoStillURL': u'http://www.telemadrid.es/sites/default/files/images/atleticomadrid_0805.jpg',
 'yearProduced': None}
```

**Comment by bdovaz** [comment]
El problema es que esas URLs devuelven acceso denegado si no contienen "?v=&fp=&r=&g=".

Y si incluyo eso (que es lo que devuelves tu) es cuando no funciona jajaja.

Para mí que el problema es el "content/type = video/x-flv" que Chromecast lo ve y lo echa para atrás. Debería devolver "video/mp4".

**Comment by aabilio** [comment]
Ya, por eso le metí esos parámetros, sino no tienes acceso al vídeo ;)
No sé cómo funciona chromcast, ni qué formatos de archivos (y/o streaming), codecs,... permite. Ahí no te puedo ayudar.
¿La app para chromecast la programas tú, o estás utilizando alguna de terceros? ¿Has probado a bajarte el vídeo y enviarlo como un fichero y no directamente en streaming desde servidores de terceros a ver si chromecast lo acepta?

**Comment by bdovaz** [comment]
Aquí están los formatos compatibles:

https://developers.google.com/cast/docs/media

La app la he programado para Android y tengo miles de descargas y casi 500 valoraciones (4,7 de 5 de nota).

Utilizo el SDK de Chromecast y yo desde que le envío la URL no se qué pasa. Acabo de poner un issue nuevo en el github del SDK de Chromecast para ver si se puede saltar esa comprobación de alguna manera.

Ahora ando añadiendo más canales (Tengo hasta ahora 14 que funcionan) y me he encontrado con este problema.

Lo de descargarlo podría hacerlo pero la gracia es que en mi aplicación pulsas en el episodio, obtiene desde pydown (o mi app para los que pydown no soporta) la url del vídeo y empieza a reproducirlo en la televisión.

**Comment by aabilio** [comment]
Pues a ver si se puede arreglar, suerte! ;)

**Comment by bdovaz** [comment]
Gracias!
