### ISSUE TITLE
Los enlaces de atresplayer no funcionan, pone "Hash invalido"

### ISSUE THREAD

**Issue by bdovaz** [aabilio/PyDownTV2#126]
Con este enlace:

http://www.pydowntv.com/api/http://www.atresplayer.com/television/series/el-secreto-de-puente-viejo/temporada-1/capitulo-814-9-5-14_2014050800114.html

Devuelve en url vídeo un JSON (como siempre). El problema es que en ese JSON devuelve "hash no válido".

https://servicios.atresplayer.com/api/urlVideoLanguage/20140508-EPISODE-00002-false/android_tablet/20140508-EPISODE-00002-false%7C1399843537%7C56658e18451131648bc3a25d9ddaa144/es.json

¿Puedes mirarlo por favor? Se está quejando bastante gente que usa la aplicación que tengo desarrollada.

Gracias!!

**Comment by aabilio** [comment]
Ya está arreglado. Pero cuando recibas a través de la API de pydowntv la URL de la API de atresplayer en vez del mp4, tienes que acceder a ella con un User-Agent de un móvil android, sino te seguirá dando hash inválido. Saludo .
Movido: https://github.com/aabilio/PyDownTV2/issues/125
