### ISSUE TITLE
eitb.tv

### ISSUE THREAD

**Issue by pakocg** [aabilio/PyDownTV2#13]
Llevo días usándo PyDownTV para descargar vídeos de eitb.tv, pero hoy da problemas:

rtmpdump --rtmp 'rtmp://cp101675.edgefcs.net/ondemand/&mp4:23/102076681001/201302/1405/102076681001_2160170703001_132574-20130212-174459-copy.mp4?**nn**=1545806548001&slist=23/102076681001/201302/109/;23/102076681001/201302/1405/;23/102076681001/201302/2533/&auth=daEdbaPbnbNb2cKbTbzaBcLc8aaaOcmdVb0-brkGda-bWG-zAyn_FGn_CIwD_ImI&aifp=rtmpeuds17' --app='ondemand?**nn**=1545806548001&slist=23/102076681001/201302/109/;23/102076681001/201302/1405/;23/102076681001/201302/2533/&auth=daEdbaPbnbNb2cKbTbzaBcLc8aaaOcmdVb0-brkGda-bWG-zAyn_FGn_CIwD_ImI&aifp=rtmpeuds17&videoId=2160173889001&lineUpId=&pubId=102076681001&playerId=893448935001' --swfUrl='http://admin.brightcove.com/viewer/us20121213.1025/federatedVideoUI/BrightcovePlayer.swf?uid=1355746343102' --playpath='mp4:23/102076681001/201302/1405/102076681001_2160170703001_132574-20130212-174459-copy.mp4?**nn**=1545806548001&slist=23/102076681001/201302/109/;23/102076681001/201302/1405/;23/102076681001/201302/2533/&auth=daEdbaPbnbNb2cKbTbzaBcLc8aaaOcmdVb0-brkGda-bWG-zAyn_FGn_CIwD_ImI&aifp=rtmpeuds17&videoId=2160173889001' --pageUrl='http://www.eitb.tv/es/#/video/2160173889001' -o 'El_Conquistador_del_Fin_del_Mundo_2010-2013_-7-.mp4'
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
ERROR: Closing connection: NetStream.Play.StreamNotFound

**Comment by garaolaza** [comment]
Confirmo este bug. "No se reconoce el tipo de contenido"

**Comment by aabilio** [comment]
@pakocg para el vídeo que a tí te da error, a mí sí me lo deja descargar (empezar a descargar vamos, no lo he probado hasta el final)
![Captura de pantalla 2013-02-26 a la s 13 43 01](https://f.cloud.github.com/assets/664712/196256/2f7f7b46-8012-11e2-9d96-06addd76822b.png)
.. [imagen adjunta]

**Comment by aabilio** [comment]
@garaolaza es error que te da a tí no es el mismo que a @pakocg, a tí ni siquiera te detecta el vídeo PyDownTV. Pásame el enlace que probaste cuando te salió ese error, o con otro que te pase lo mismo ;)

**Comment by garaolaza** [comment]
Ok, aquí está el dump:

pydowntv.py http://www.eitb.tv/eu/bideoa/2168035591001
[INFO VERSIÓN] Comprobando si existen nuevas versiones de PyDownTV 
[INFO VERSIÓN] Tu versión de PyDownTV es la más reciente 

[ URL ] http://www.eitb.tv/eu/bideoa/2168035591001 
[INFO] EITB 
[!!!] No se reconoce el tipo de contenido

**Comment by aabilio** [comment]
@garaolaza, ¿estás usando la versión de PyDownTV2 de aquí de GitHub o el antiguo de PyDownTV?
Si usas el antiguo, usa el nuevo. Si ya usabas el nuevo prueba a bajarte los últimos cambios ;)

**Comment by garaolaza** [comment]
Pues lo siento,
- Lo he clonado del git
- sudo python setup.py install
- pydowntv.py http://www.eitb.tv/eu/bideoa/2168035591001
  [INFO VERSIÓN] Comprobando si existen nuevas versiones de PyDownTV 
  [!!!] ERROR al comprobar la versión del cliente 

[ URL ] http://www.eitb.tv/eu/bideoa/2168035591001 
[INFO] Euskal Irrati Telebista 
No se reconoce el tipo de contenido 

Bueno, si no reproducís el problema será algún tema mío.

**Comment by aabilio** [comment]
Iba a hacer pruebas con el enlaces que me dices desde una versión recién instalada de PyDownTV2, pero parece que ese enlace si alguna vez existió, ahora parece no estar accesible (no me carga desde el navegador).
Existe algún otro enlace todavía disponible que te de el mismo error para este canal?

**Comment by aabilio** [comment]
@garaolaza parece que el error se encuentra en la versión de la web según el idioma. Mientras no arreglo este error, parece que se soluciona si eliges la versión en español de la página (al lado del logo del canal, arriba a la izquierda, seleccionar ES en vez e EU).
Espero corregirlo en los próximos días de todas maneras ;)

**Comment by aabilio** [comment]
@garaolaza parece que ya está solucionado (http://web.pydowntv.com/?url=http%3A//www.eitb.tv/eu/%23/bideoa/2127283747001) en el script debería de funcionar correctamente también.
Saludos.

**Comment by pakocg** [comment]
@aabilio: Estoy probando con otro video de eitb.com y ahora si descargar correctamente. Gracias.
