### ISSUE TITLE
Petición de nuevo canal - TPA (TV Principado de Asturias)

### ISSUE THREAD

**Issue by nachofr** [aabilio/PyDownTV2#132]
La dirección web donde están los programas es la siguiente:

http://www.rtpa.es/alacarta

**Comment by aabilio** [comment]
El canal RTPA es uno de los ya soportados por PyDownTV pero acabo de comprobar ahora que está fallando.
Cambio el sentido de "Petición" a "Bug" y queda pendiente de supervisión.
Saludos.

**Comment by aabilio** [comment]
He estado corrigiendo por encima parte de los problemas. Ejemplo: http://web.pydowntv.com/?url=http%3A//www.rtpa.es/video%3ATPA%2520Noticias.%2520Primera%2520Edicion_1401466078.html

Si encuentras algún vídeo que no funcione, por favor, repórtalo. Saludo.
