### ISSUE TITLE
No puedo bajar vídeos de TV3

### ISSUE THREAD

**Issue by simonbcn** [aabilio/PyDownTV2#134]
Estoy intentando bajar un programa de TV3 a través de estas dos URLs: http://www.tv3.cat/videos/3491850/Veterinaris--Capitol-62 y http://www.tv3.cat/3alacarta/#/videos/3491850 pero en ambos casos da error:

```
[ URL ] http://www.tv3.cat/3alacarta/#/videos/3491850 
[INFO] Televisió de Catalunya 

DESCARGAR: 
---------------------------------------------------------------- 
[ URL DE DESCARGA FINAL ] http://mp4-high-dwn.media.tv3.cat/g/tvcatalunya/6/1/1303894630916.mp4 
[INFO] Presiona "Ctrl + C" para cancelar 

[Destino]  Veterinaris-Capitol_62.mp4 
HTTP Error 404: Not Found
```

Vía web no he podido probar ya que http://www.pydowntv.com/ da un error `503 Over Quota`

**Comment by aabilio** [comment]
Con los cambios que acabo de subir debería estar funcionando bien ahora. Baja la última versión y échale un ojo ;)

**Comment by simonbcn** [comment]
Sí, ahora funciona. Muchas gracias. :smiley: :thumbsup:
