### ISSUE TITLE
De buenas a primeras aparece un fallo recurrente que no me deja descargar

### ISSUE THREAD

**Issue by RULOGARRULO** [aabilio/PyDownTV2#14]
Se ha detectado error:
ERROR al recuperar el vídeo: mitele.es: RTMP no soportado para el canal por ahora.

**Comment by aabilio** [comment]
Te da el error en muchos vídeos de diferentes programas? Algunos vídeos ya sabía que no estaban soportados, pero no eran muchos. Con qué vídeos te está dando?
