### ISSUE TITLE
Peticion: Descargar trozos de programas completos

### ISSUE THREAD

**Issue by nsnlqnbr** [aabilio/PyDownTV2#143]
Hola buenas :) Quisiera pediros que si podriais, como he mencionado en el titulo, poder descargar trozos o fragmentos de programas/series completas. EJ: quiero descargar una escena de lqsa pero no esta cortado y tengo que descargar el capitulo entero y recortarlo por mi mismo, pero si hubiera una funcion online para cortar facilitaria mucho las cosas. Muchas gracias por vuestra atencion y espero que me respondais pronto.

**Comment by aabilio** [comment]
Lo siento, PyDownTV no tiene ni procesa los vídeos de los que ofrece los enlaces. Solo dice donde se encuentra alojado, por lo que son las cadenas las que tienen que ofrecer ese trozo.
Has probado a ver si tienen ese trozo la cadena en telecinco y no en MiTele?
Saludos.
