### ISSUE TITLE
error en la descarga de un video de EITB

### ISSUE THREAD

**Issue by gerardomoll** [aabilio/PyDownTV2#146]
Este enlace de la EITB me da error al descargarlo, qué puedo hacer para descargarlo?
http://www.eitb.tv/es/video/bilbao-ciudades-en-el-tiempo/2604897079001/2605836830001/bilbao-en-el-tiempo/
Muchas gracias
Un saludo

**Comment by denobisipsis** [comment]
http://uds.ak.o.brightcove.com/102076681001/102076681001_2605864112001_174741-20130814-160351-copy.mp4?__nn__=1497926354001&slist=102076681001/&auth=daEbCa7chcMaBaadSaNbNc7bVbLd_cPaJdY-bt8Xiq-bWG-slGCyrzw_yAAq_JDEA_EtC&aifp=bcosuds

**Comment by aabilio** [comment]
Parece que vuelve a funcionar ;)
