### ISSUE TITLE
RTVE falla

### ISSUE THREAD

**Issue by iskraelectrica** [aabilio/PyDownTV2#147]
Saludos.

He probado varios videos y falla la descarga.
He probado con el script, con la web y con un programa propio.

http://www.rtve.es/alacarta/videos/la-forja-de-un-rebelde/forja-rebelde-capitulo-3/2714815/
http://www.rtve.es/alacarta/videos/la-forja-de-un-rebelde/forja-rebelde-capitulo-1/2696734/

Todos acaban igual:
Authorization Required
 This server could not verify that you are authorized to access the document you requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

Algunos incluso dan erro al intentar extraer la URL del vídeo, como este:
http://www.rtve.es/alacarta/videos/la-forja-de-un-rebelde/forja-rebelde-capitulo-5/457334/

Miraré por mi parte, con RTVE tengo algo de experiencia, y ya te contaré si encuentro algo.

**Comment by iskraelectrica** [comment]
RTVEPlayerVideo.swf es defecha 26/08/2014
La contra s e ñ a ha cambiado "y e L & d a D 3", aunque creo que esto ya lo sabes. Ya que mi programa no desembarullaba el xml y ahora sí, pero sigue tropezando con
 HTTP Error 401: Unauthorized
o 
HTTP Error 403: Forbidden, 
según el que pruebe de los que salen en el xml.

**Comment by forestrf** [comment]
El resultado que funciona para el último vídeo es el flv en lugar del mp4. Para los otros dos es el mp4.

**Comment by denobisipsis** [comment]
Para todos sigue funcionando el metodo png, para el ultimo

http://mvodt.lvlt.rtve.es/resources/TE_NGVA/mp4/8/9/1320481156898.mp4?nvb=20140830011115&nva=20140830071115&token=0753902edc2a607e9d347
,

**Comment by iskraelectrica** [comment]
en http://www.pydowntv.com/ no funciona nínguno. Veré si estoy desactualizado con el script, aunque creo que no.
denobis, el enlace que facilitas da esto al bajarlo:

<HTML><HEAD>
<TITLE>401 Authorization Required</TITLE>
</HEAD>
<BODY>

<H1>Authorization Required</H1>

This server could not verify that you
are authorized to access the document you
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.<P>
</BODY></HTML>

**Comment by iskraelectrica** [comment]
"La forja de un rebelde - El rodaje desde dentro.mp4" http://mvodt.lvlt.rtve.es/resources/TE_NGVA/flv/2/0/1237979385702.flv?nvb=20140830091313&nva=20140830151313&token=0831458c47da563173117
El xml obtenido es este

<?xml version='1.0'?><quality><preset order='0' type='Alta'><response code='ok' geolocalizado='false' GMTEnabled='' GMTDisabled=''><url tipo='' provider='AKAMAI_STR-1350'>http://mvodt.lvlt.rtve.es/resources/TE_NGVA/flv/2/0/1237979385702.flv?nvb=20140830091313&amp;nva=20140830151313&amp;token=0831458c47da563173117</url><url tipo='' provider='AKAMAI_STR-1250'>http://l3-onlinefs.rtve.es/resources/TE_NGVA/mp4/0/0/1100000000000.mp4</url></response></preset><preset order='1' type='Media'><response code='ok' geolocalizado='false' GMTEnabled='' GMTDisabled=''><url tipo='' provider='AKAMAI_STR-1350'>http://mvodt.lvlt.rtve.es/resources/TE_NGVA/mp4/9/7/1320480269279.mp4?nvb=20140830091313&amp;nva=20140830151313&amp;token=037967bf08cfa6cb1638a</url><url tipo='' provider='AKAMAI_STR-1250'>http://l3-onlinefs.rtve.es/resources/TE_NGVA/mp4/0/0/1100000000000.mp4</url></response></preset></quality>

y todos dan error.

**Comment by iskraelectrica** [comment]
este funciona
http://mvod.lvlt.rtve.es/resources/TE_NGVA/flv/2/0/1237979385702.flv

y este, que es el que viene en el  xml no
http://mvodt.lvlt.rtve.es/resources/TE_NGVA/flv/2/0/1237979385702.flv

**Comment by iskraelectrica** [comment]
Es algo peculiar de 'La forja de un rebelde' ya que los enlaces para 'Isabel' salen normalitos, sin la t de más.
Mosqueante.
