### ISSUE TITLE
Los links de RTVE piden user y pass

### ISSUE THREAD

**Issue by nonamenoway** [aabilio/PyDownTV2#149]
Los links de RTVE están pidiendo user y pass al intentar reproducirlos.

http://www.rtve.es/alacarta/videos/telediario/comienza-grabacion-nueva-temporada-masterchef-junior/2738155/
------>
http://mvodt.lvlt.rtve.es/resources/TE_NGVA/mp4/1/5/1409690494951.mp4

**Comment by denobisipsis** [comment]
http://mvod.lvlt.rtve.es/resources/TE_NGVA/mp4/1/5/1409690494951.mp4?nvb=20140905083055&nva=20140905143055&token=059b4b34bf73958dd50b3

**Comment by nonamenoway** [comment]
Gracias Denobis.
El link de ejemplo en sí no me importa, sino cómo modificar el código para recuperar las URL correctas incluyendo los parámetros que has puesto (nvb,nva,token)
Se está preparando la actualización del código ?.

**Comment by aabilio** [comment]
En cuanto pueda lo arreglo. Lo siento pero ahora mismo no tengo ni un
minuto para echarle un ojo. Saludos.

aabilio - http://web.pydowntv.com
GPG id 81D115C4 Abilio Almeida Eiroa (aabilio)
SIP: aabilio@ekiga.net Skype: @a_abilio

**Comment by aabilio** [comment]
Parece que ya va mejor

**Comment by nonamenoway** [comment]
Hola aabilio,

No, está igual que estaba.
Lo que ocurre es que sólo protegen con user&pass los más recientes.

http://www.rtve.es/alacarta/videos/saber-y-ganar/saber-ganar-12-09-14/2754043/
->
http://mvodt.lvlt.rtve.es/resources/TE_NGVA/mp4/6/4/1410533977446.mp4

Pide user&pass.

**Comment by aabilio** [comment]
*no debería, digo (ese formato)
On Sep 14, 2014 6:31 PM, aabilio@gmail.com wrote:

Pydowntv  o debería dar ese enlace..
On Sep 14, 2014 4:58 PM, "nonamenoway" notifications@github.com wrote:

Hola aabilio,

No, está igual que estaba.
Lo que ocurre es que sólo protegen con user&pass los más recientes.

http://www.rtve.es/alacarta/videos/saber-y-ganar/saber-ganar-12-09-14/2754043/
->
http://mvodt.lvlt.rtve.es/resources/TE_NGVA/mp4/6/4/1410533977446.mp4

Pide user&pass.

**Comment by aabilio** [comment]
Pydowntv  o debería dar ese enlace..

**Comment by nonamenoway** [comment]
Pues es el enlace que devuelve pydowntv.com también...
Y hoy, pasados ya 3 días, ese enlace del ejemplo ya no pide user y pass al intentar reproducirlo.

Revisaré si ya no pide user&pass en ninguno o sigue pidiéndolo en vídeos más recientes.

x denobis:
¿Tienes el algoritmo que calcula la url que has posteado?.
Si lo tienes, yo mismo modifico el script y le envío los cambios a aabilio.

Gracias.

**Comment by aabilio** [comment]
No pydowntv.com, no da el mismo enlace, fíjate ;) (en la sutileza está el truco)

**Comment by nonamenoway** [comment]
Got it !!!
Gracias :-)

**Comment by nonamenoway** [comment]
En el código de github está actualizado ?.
Supongo que (otra vez) no estoy usando la última versión...

**Comment by aabilio** [comment]
@nonamenoway no, ahora lo subo

**Comment by aabilio** [comment]
@nonamenoway ya -> https://github.com/aabilio/PyDownTV2/commit/57cb1312a1ad66f9e6900e99818726368c10c495

**Comment by nonamenoway** [comment]
Muchas gracias
