### ISSUE TITLE
Problems downloading a link

### ISSUE THREAD

**Issue by robmir** [aabilio/PyDownTV2#15]
http://desprogresiva.antena3.com/mp_seriesh4/RTMPE/2013/02/27/00003/002.mp4

No hay forma de guardar  la 2da parte de las seis que forman el capitulo 34,  al bajar este link da error

**Comment by aabilio** [comment]
Con qué enlace tienes problemas (de antena3).
Los enlaces que devuelve PyDownTV son los que se obtienen de rastrear el vídeo. Si alguno de esos enlaces no está accesible es debido a algún problema en sus servidores.
Se ve la parte dos desde la web?

**Comment by robmir** [comment]
Si, la parte 2 si se ve desde la web

**Comment by robmir** [comment]
He bajado mas de 33 capitulos para mi esposa de antena 3 y es primera vez que aparece este problema , intento guardar y un segundo despues termina, y en vez de decir pydowntv dice 0 bytes-anten3.com cuando cualquiera de los otros dicen 51.5 MB-pydowntv.com

**Comment by aabilio** [comment]
Pon aquí el enlace de la web de donde está el vídeo que intentas descargar para echarle un ojo a ese estilo especificamente

**Comment by robmir** [comment]
http://desprogresiva.antena3.com/mp_seriesh4/RTMPE/2013/02/27/00003/002.mp4

**Comment by aabilio** [comment]
No, me refería al enlace que le dices a PyDownTV ;)

**Comment by robmir** [comment]
http://www.antena3.com/videos/amar/temporada-1/capitulo-34.html     es el enlace original y el segmento que no quiere bajar es el 
http://desprogresiva.antena3.com/mp_seriesh4/RTMPE/2013/02/27/00003/002.mp4

**Comment by aabilio** [comment]
Parece que ya está solucionado: http://web.pydowntv.com/?url=http://www.antena3.com/videos/amar/temporada-1/capitulo-34.html

Si puedes hacer pruebas con algún que otro vídeo más y confirmar sería bienvenido.

Gracias por reportar. Saludos.

**Comment by robmir** [comment]
Pues parece que antena 3 resolvio el problema por que hoy probe y ya se pudo guardar perfectamente, gracias por estar pendiente.

**Comment by aabilio** [comment]
@robmir es que he estado haciendo cambios en PyDownTV para que te funcionara bien ;) El problema es que ahora el funciona mal a otros. Tengo que encontrar un punto medio ;)

**Comment by robmir** [comment]
ooops, lo curioso es que siemprre funciono bien hasta este segmento en particular !!!!!!

**Comment by robmir** [comment]
por lo pronto he podido bajar el 35, el 36 y el 37 perfectamente.
