### ISSUE TITLE
Problemas con los programas 60 minutos de Eitb

### ISSUE THREAD

**Issue by Ritxard** [aabilio/PyDownTV2#16]
Buenas

No consigo hacer descargar los programas "60 minutos" de EITB, como este:

rtmpdump --rtmp 'rtmp://cp150446.edgefcs.net/ondemand/&mp4:102076681001/102076681001_2101582342001_128771-20130117-225931.mp4?**nn**=1497926354001&slist=102076681001/&auth=daEdQd7cDdqa6axcvdaaKbecobFadcZbban-brnkJG-bWG-moGCAsxw_yDzn_ACBz_FqC&aifp=bcosuds' --app='ondemand?**nn**=1497926354001&slist=102076681001/&auth=daEdQd7cDdqa6axcvdaaKbecobFadcZbban-brnkJG-bWG-moGCAsxw_yDzn_ACBz_FqC&aifp=bcosuds&videoId=2101343573001&lineUpId=&pubId=102076681001&playerId=893448935001' --swfUrl='http://admin.brightcove.com/viewer/us20121213.1025/federatedVideoUI/BrightcovePlayer.swf?uid=1355746343102' --playpath='mp4:102076681001/102076681001_2101582342001_128771-20130117-225931.mp4?**nn**=1497926354001&slist=102076681001/&auth=daEdQd7cDdqa6axcvdaaKbecobFadcZbban-brnkJG-bWG-moGCAsxw_yDzn_ACBz_FqC&aifp=bcosuds&videoId=2101343573001' --pageUrl='http://www.eitb.tv/es/#/video/2101343573001' -o '60_minutos_-Azkuna_el_mejor_alcalde_del_mundo-.mp4'

Agradecería vuestra ayuda, muchas gracias!

**Comment by aabilio** [comment]
Cuál es el problema exactamente?

**Comment by Ritxard** [comment]
Buenas tardes
Es posible que no esté llevando a cabo todos los pasos correctamente, pero cuando intento descargar, me da error. Me puedes indicar los pasos correctos? Muchas gracias.
 Date: Mon, 4 Mar 2013 06:45:26 -0800

**Comment by aabilio** [comment]
Pero estás utilizando rtmpdump?
Para descargas vídeo de EITB se necesita rtmpdump, echa un vistazo a esta ayuda para comprender cómo: http://web.pydowntv.com/ayuda#DescargarRtmp

**Comment by Ritxard** [comment]
Si claro, pero me da
un error. Algun paso debo estar haciendo mal.
Voy a ver el tutorial y mañana lo aplico,
y si me da error te envio una captura de pantalla.
Muchas gracias.

**Comment by aabilio** [comment]
Aquí hay algún reporte sobre EITB anteriores por si le quieres echar un vistazo también: https://github.com/aabilio/PyDownTV2/issues/search?q=eitb

**Comment by Ritxard** [comment]
Buenos días En este tutorial me basé para seguir los pasos Voy a hacer nuevamente la prueba, y en función de los resultados te comento. Muchas gracias.
 Date: Mon, 4 Mar 2013 09:28:34 -0800

**Comment by Ritxard** [comment]
Según el tutorial de mas abajo, voy a ir haciendo los pasos y te los voy comentando:  1.- Descargo la versión de rtmpdump para Windows. 2.- Ejecuto rtmpdump en Windows. Es decir, copio rtmpdump.exe y pego en system32. Posteriormente le doy a inicio-buscar y escribo "cmd" y me sale la consola (captura de pantalla 1).
3.- Copio el siguiente video  http://www.eitb.tv/es/#/video/2101343573001 en PyDownTV y me sale lo siguiente (captura de pantalla 2). ¿Hasta aquí todo correcto? Ahora llega la parte crítica:  Por lo que entiendo, he de copiar y pegar la secuencia que aparece en la captura de pantalla 2: rtmpdump --rtmp 'rtmp://cp150446.edgefcs.net/ondemand/&mp4:102076681001/102076681001_2101605154001_128771-20130117-225931.mp4?**nn**=1497926354001&slist=102076681001/&auth=daEcTbycWdWcfa8aNdramaVcwdXdYdLcXbr-brnzFW-bWG-pmBCzszy_yAxv_HCxy_FoE&aifp=bcosuds' --app='ondemand?**nn**=1497926354001&slist=102076681001/&auth=daEcTbycWdWcfa8aNdramaVcwdXdYdLcXbr-brnzFW-bWG-pmBCzszy_yAxv_HCxy_FoE&aifp=bcosuds&videoId=2101343573001&lineUpId=&pubId=102076681001&playerId=893448935001' --swfUrl='http://admin.brightcove.com/viewer/us20121213.1025/federatedVideoUI/BrightcovePlayer.swf?uid=1355746343102' --playpath='mp4:102076681001/102076681001_2101605154001_128771-20130117-225931.mp4?**nn**=1497926354001&slist=102076681001/&auth=daEcTbycWdWcfa8aNdramaVcwdXdYdLcXbr-brnzFW-bWG-pmBCzszy_yAxv_HCxy_FoE&aifp=bcosuds&videoId=2101343573001' --pageUrl='http://www.eitb.tv/es/#/video/2101343573001' -o '60_minutos_-Azkuna_el_mejor_alcalde_del_mundo-.mp4' ¿Es correcto? Si copio y pego esto en la consola, me aparece lo siguiente (captura de pantalla 3). Pues bien, ahí está el error. Algo mal debo estar haciendo seguro, por favor, indícamelo. Muchas gracias.  Date: Mon, 4 Mar 2013 09:28:34 -0800

**Comment by aabilio** [comment]
No veo las capturas de pantalla.. :S por lo tanto no puedo ver el error que te sale, pero en principio lo estás haciendo bien ;)

Prueba con este comando:
rtmpdump --rtmp 'rtmp://cp150446.edgefcs.net/ondemand/&mp4:102076681001/102076681001_2101582342001_128771-20130117-225931.mp4?**nn**=1497926354001&slist=102076681001/&auth=daEdWcWb.drbQcbc8d4dAbTc1dvbOaBcPcl-brnEXq-bWG-snFBtsyx_ABzm_GFBz_FpE&aifp=bcosuds' --app='ondemand?**nn**=1497926354001&slist=102076681001/&auth=daEdWcWb.drbQcbc8d4dAbTc1dvbOaBcPcl-brnEXq-bWG-snFBtsyx_ABzm_GFBz_FpE&aifp=bcosuds&videoId=2101343573001&lineUpId=&pubId=102076681001&playerId=893448935001' --swfUrl='http://admin.brightcove.com/viewer/us20121213.1025/federatedVideoUI/BrightcovePlayer.swf?uid=1355746343102' --playpath='mp4:102076681001/102076681001_2101582342001_128771-20130117-225931.mp4?**nn**=1497926354001&slist=102076681001/&auth=daEdWcWb.drbQcbc8d4dAbTc1dvbOaBcPcl-brnEXq-bWG-snFBtsyx_ABzm_GFBz_FpE&aifp=bcosuds&videoId=2101343573001' --pageUrl='http://www.eitb.tv/es/#/video/2101343573001' -o '60_minutos_-Azkuna_el_mejor_alcalde_del_mundo-.mp4'

Sino te va, prueba con este (es el mismo, pero cambiando las comillas simples por dobles, para descargar errores):
rtmpdump --rtmp "rtmp://cp150446.edgefcs.net/ondemand/&mp4:102076681001/102076681001_2101582342001_128771-20130117-225931.mp4?**nn**=1497926354001&slist=102076681001/&auth=daEdWcWb.drbQcbc8d4dAbTc1dvbOaBcPcl-brnEXq-bWG-snFBtsyx_ABzm_GFBz_FpE&aifp=bcosuds" --app="ondemand?**nn**=1497926354001&slist=102076681001/&auth=daEdWcWb.drbQcbc8d4dAbTc1dvbOaBcPcl-brnEXq-bWG-snFBtsyx_ABzm_GFBz_FpE&aifp=bcosuds&videoId=2101343573001&lineUpId=&pubId=102076681001&playerId=893448935001" --swfUrl="http://admin.brightcove.com/viewer/us20121213.1025/federatedVideoUI/BrightcovePlayer.swf?uid=1355746343102" --playpath="mp4:102076681001/102076681001_2101582342001_128771-20130117-225931.mp4?**nn**=1497926354001&slist=102076681001/&auth=daEdWcWb.drbQcbc8d4dAbTc1dvbOaBcPcl-brnEXq-bWG-snFBtsyx_ABzm_GFBz_FpE&aifp=bcosuds&videoId=2101343573001" --pageUrl="http://www.eitb.tv/es/#/video/2101343573001" -o "60_minutos_-Azkuna_el_mejor_alcalde_del_mundo-.mp4"

La única diferencia del comando que te da a tí PyDownTV y el que me da a mí es el valor de "&auth" que aparece en el comando...
