### ISSUE TITLE
Que occurre con ciertos videos que nunca se descargan

### ISSUE THREAD

**Issue by mardojin** [aabilio/PyDownTV2#17]
Hay ciertos programas que no puedo descargar y no comprendo por que, cuando descargo perfectamente muchos otros. Por ejemplo:

Comando Actualidad El precio de alquilar, de RTVE a la carta. Este es el enlace que me da pydowntv:
Comando Actualidad El precio de alquilar, Comando Actualidad A la Carta 
Cuando intento descargarlo me sale esto:

Forbidden
You don't have permission to access /auth-content-targetting/NA/CA/ on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

Mas o menos diciendome que no tengo permiso para acceder al contenido de el servidor de RTVE. Por que si descargo muchos otros programas? Tambien me ocurre con Grandes Documentales y otros programas. No lo entiendo. Que tienen de especial estos programas que no lo tengan todos los otros que descargo?

Si tiene alguna solucion se lo agradeceria mucho.

Dolores.

**Comment by aabilio** [comment]
Me puedes poner el enlace de RTVE a ese vídeo en concreto para echarle un vistazo?

**Comment by mardojin** [comment]
Hola y gracias por tu ayuda.  Este es el primer enlace, de uno de los programas que antes podia descargar sin ningun problema y de repente no me deja:

http://www.rtve.es/alacarta/videos/la-noche-tematica/noche-tematica-reza-para-diablo-regrese-infierno/1714100/

Este es el otro:

http://www.rtve.es/alacarta/videos/grandes-documentales/grandes-documentales-gigantes-del-mar-voces-del-mar/1719147/

Hace como mes y medio o dos meses de repente no me dejaba descargarlo. 

Gracias.

**Comment by aabilio** [comment]
¿Te encuentras fuera de España? Puede ser por que estén Geolocalizados. Si es así, en estos casos, puedes probar a editar a mano la URL que te proporciona PyDownTV para descargar estos vídeos.
En este supuesto, puedes probar lo siguiente y si te funciona nos lo comentas ;)

En las URL que te proporciona PyDownTV se suele encontrar una parte de la siguiente forma: /TE_XXXXX/ prueba a cambiar esta parte por TE_NGVA.
Esto lo sospecho debido a que para la primera URL que me pasas, PyDownTV devuelve la siguiente: http://media5.rtve.es/resources/TE_GLESP/mp4/3/2/1362876047123.mp4
Este "TE_GLESP" me hace pensar que tenga que ver algo con "GeoLocalizado a ESPaña"

Si definitivamente no te encuentras fuera de España (o no te encontrabas cuando intentaste descargar estos vídeos), no sé qué podría estar pasando, yo puedo acceder a ellos perfectamente.

Saludos.

**Comment by mardojin** [comment]
Si, estoy en Canada.  Voy a probar lo que me dices y si me resulta te lo dire.

Muchas gracias.

**Comment by mardojin** [comment]
Hola de
nuevo.  Te escribo para darte las gracias
por tu ayuda. Hice como me dijiste y puse ngva. 
¡Ha funcionado
perfectamente!
 
Muchas gracias.

**Comment by aabilio** [comment]
He añadido un poco de código a la aplicación para que si detecta que se está fuera de España y PyDownTV devuelva una URL con TE_GLESP lo cambie automáticamente por TE_NGVA. Espero que funciones bien.
Solo disponible con el modo de descarga normal (Ni con "A Granel", ni en la API). Cierro Issue.
Saludos.

**Comment by mardojin** [comment]
De nuevo, muchisimas gracias!
