### ISSUE TITLE
ERROR al recuperar el vídeo: mitele.es: RTMP no soportado para el canal por ahora.

### ISSUE THREAD

**Issue by satelite** [aabilio/PyDownTV2#18]
Hola!!

Al intentar descargar el archivo via web ... http://www.mitele.es/series-online/llama-a-la-comadrona/temporada-1/capitulo-1/ me sale el error mencionado arriba. Otros archivos de mitele van bien, asi que si estoy haciendo algo mal no se que puede ser. 

Gracias.

**Comment by aabilio** [comment]
Los vídeos que MiTele proporciona a través del protocolo RTMP aun no están soportados por PyDownTV. Sorry.

**Comment by satelite** [comment]
Gracias por la respuesta. Y muchisimas gracias por el curro desinteresado que tiene todo esto.
