### ISSUE TITLE
No encuentro el video descargado

### ISSUE THREAD

**Issue by rlcortes** [aabilio/PyDownTV2#19]
Tras seguir el paso a paso que indicas en la web de PyDown para obtener el siguiente video http://www.crtvg.es/informativos/un-grupo-de-cientificos-galegos-avanza-na-investigacion-da-metastase-544274 veo que rtmdump.exe finaliza la descarga indicando el la ventana de cmd "Download complete".

En teoría el video debería estar en la carpeta raíz C, en la práctica... no lo veo por ninguna parte, debe ser una pregunta muy tonta pero, ¿cómo lo localizo?

**Comment by aabilio** [comment]
Si te fijas, en la consola, antes de pegar el comando aparece una ruta de archivos. Es en esa ruta donde se debería haber descargado el vídeo. Ejemplo: C:\rlcortes>

**Comment by rlcortes** [comment]
Cierto! Muchas gracias, ya imaginé que sería una tontería.

Ahora que lo tengo localizado, veo que está en un formato que uso comunmente, .mp4, para reproducir videos, sin embargo, cuando lo intento abrir se me indica que:

"El Reproductor de Windows Media no puede reproducir el archivo. Es posible que el Reproductor no admita el tipo de archivo o el códec usado para comprimir el archivo."

Comprobado con otros videos, reproduzco sin problemas el .mp4, además, un vídeo que en la web dura menos de 2 minutos me tiene un peso de 850 MB y un tiempo superior a 1 hora!!

Disculpa tanta pregunta.

**Comment by rlcortes** [comment]
Datos adicionales:

En propiedades del video, el apartado Duración, Frame width, Frame height, Data rate, Total bitrate y Frame rate están completamente vacíos, a diferencia de cualquier otro vídeo.

¿Sugieres descargar de nuevo el vídeo modificando algún parámetro?

**Comment by aabilio** [comment]
Lo de que el vídeo sea más grande de lo que tendría que ser es normal. Normalmente CRTVG pone pedazos de vídeos más grandes incrustados en los reproductores online, sin embargo, para descargarlos, es necesario hacerlo en su totalidad. Lo que es raro es que el vídeo no se reproduzca, ¿has probado con VLC (http://www.videolan.org/)? puede ser algún problema de codecs ;)
