### ISSUE TITLE
El icono del botón en la barra de apps de Firefox no aparece

### ISSUE THREAD

**Issue by simonbcn** [aabilio/PyDownTV2#2]
Firefox 17.0.1
Ubuntu 12.04 64 bits

El icono del botón en la barra de apps de Firefox no aparece

![captura_1220_13:05:42](https://f.cloud.github.com/assets/428231/24331/e2805b42-4a9e-11e2-984b-cdd815587be6.jpg)

**Comment by aabilio** [comment]
Gracias por reportar, le echaré un vistazo ;)

**Comment by aabilio** [comment]
Esto debería estar solucionado con la actualización del plugin, no?

**Comment by simonbcn** [comment]
Sí, está solucionado con la versión 0.3 (se actualizó hace unos días).
Gracias. Un saludo.
