### ISSUE TITLE
 De repente problemas con mitele de Telecinco. 

### ISSUE THREAD

**Issue by mardojin** [aabilio/PyDownTV2#21]
Han vuelto a cambiar algo en Telecinco mitele?  De repente no puedo descargar nada. Me pide contraseña y dice que no tengo autorización.

Gracias.

**Comment by aabilio** [comment]
Parece que sí, esta noche tengo un hueco, a ver si lo puedo solucionar ;)

**Comment by mardojin** [comment]
Siempre estan haciendo igual!

**Comment by aabilio** [comment]
Si entras a través de http://www.pydowntv.com/ se deberían solucionar temporalmente los errores..

**Comment by mardojin** [comment]
Hola de nuevo. Pues no todavia no por que lo acabo de intentar y sigue ocurriendo lo mismo.

Gracias.

**Comment by aabilio** [comment]
Lo solucioné por la noche y esta mañana ha vuelto a fallar. Estoy trabajando ahora en ello ;)

**Comment by aabilio** [comment]
Ahora está solucionando, a ver cuánto dura..

**Comment by mardojin** [comment]
Siento molestarte
de nuevo pero no me funciona. Parece que no les da la gana de que nadie descargue
nada.

**Comment by mardojin** [comment]
Muchísimas gracias. Eso digo
yo también. A ver cuánto tardan en fastidiarnos otra vez.

**Comment by aabilio** [comment]
Nos han vuelto a bloquear

**Comment by mardojin** [comment]
Son idiotas.

**Comment by aabilio** [comment]
Los problemas deberían de estar solucionados ya

**Comment by mardojin** [comment]
No....sigue igual. Parece que esta vez lo han puesto dificil. 

Gracias por intentarlo.

**Comment by aabilio** [comment]
Pues no he cambiado nada y yo sí puedo descargar. Me puedes poner un enlace con el que te falle?

**Comment by xuxiao0427** [comment]
Saludos,
Ahora tampoco puedo descargar los vídeos de telecinco, por ejemplo los últimos capítulos de La Noche de José Mota. Se puede detectar el enlace, pero tampoco reacciona al dar ¨guardar como...¨. Y si doy con el enlace, primero aparece una página de Google de redirección, después una de ¨401 Authorization Required¨. No sé qué ha pasado, nos bloquean otra vez?

**Comment by aabilio** [comment]
Eso parece

**Comment by aabilio** [comment]
Aunque acabo de probar y a mi si me va con esos vídeos..

**Comment by xuxiao0427** [comment]
ah... no sé si es por razón de países, pues los estoy descargando desde China...
Pero hace unas semanas podía descargar los vídeos perfectamente.

**Comment by aabilio** [comment]
ah pues sí puede ser :S puede que para esos capítulos hayan incluído geo bloqueo.. sorry

**Comment by xuxiao0427** [comment]
No pasa nada. ¡Muchísimas gracias por su trabajo!
