### ISSUE TITLE
No descarga vídeos de Cuarto Milenio

### ISSUE THREAD

**Issue by Atsmcc** [aabilio/PyDownTV2#22]
Buenas tardes:
Había estado descargando los vídeos de Cuarto Milenio Temporada 2. El último que descargué ayer lunes 18 fue el Capítulo 76, pero hoy que intento descargar el Capítulo 77, el enlace no aparece como archivo mp4, sino como página HTML. Intenté con el Capítulo 78, pero el resultado fue el mismo. ¿A qué se debe esto? Ayuda por favor, ya que son muy interesantes los temas. Por su atención y solución, Gracias.

**Comment by aabilio** [comment]
Sí, estoy al corriente de este fallo (falla todo MiTele), es más, estoy haciendo cambios para que funcione todo y ahora mismo no está ni disponible la web a través de http://web.pydowntv.com
Si entras a través de http://www.pydowntv.com/ todo debería de funcionar correctamente ;)

**Comment by Atsmcc** [comment]
Muy buenas tardes:
Quiero agradecer infinitamente el haber corregido los problemas en la página de Mitele. Ayer todavía no funcionaba, pero hoy que lo intenté nuevamente y pude seguir descargando los capítulos de Cuarto Milenio.
Un cordial y afectuoso saludo. 

 Antes solía ser indeciso, ahora... no estoy tan seguro 

Anthony McCartney

Atsmcc

Date: Tue, 19 Mar 2013 18:34:34 -0700

**Comment by Atsmcc** [comment]
Buen día:
nuevamente con la molestia de no poder descargar el Capítulo 9 de la Temporada 9. Puedo verlo online sin ningún problema, pero al querer descargarlo, me manda mensaje: ERROR al recuperar el vídeo: mitele.es: No se puede obenter enlaces: Deadline exceeded while waiting for HTTP response from URL: http://www.mitele.es/programas-tv/cuarto-milenio/temporada-9/programa-339/
Esperando pueda solucionarlo, me despido enviándole un cordial saludo.
Atsmcc

 Antes solía ser indeciso, ahora... no estoy tan seguro 

Anthony McCartney

Atsmcc

From: atsmcc@hotmail.com
To: reply@reply.github.com
Subject: RE: [PyDownTV2] No descarga vídeos de Cuarto Milenio (#22)
Date: Thu, 21 Mar 2013 18:04:55 -0600

Muy buenas tardes:
Quiero agradecer infinitamente el haber corregido los problemas en la página de Mitele. Ayer todavía no funcionaba, pero hoy que lo intenté nuevamente y pude seguir descargando los capítulos de Cuarto Milenio.
Un cordial y afectuoso saludo. 

 Antes solía ser indeciso, ahora... no estoy tan seguro 

Anthony McCartney

Atsmcc

Date: Tue, 19 Mar 2013 18:34:34 -0700
