### ISSUE TITLE
versión web de PyDownTV añadir a la pagina conversores de video

### ISSUE THREAD

**Issue by carabo69** [aabilio/PyDownTV2#24]
les sugiero esto puesto que antena 3 tv ahora esta empezando a trabajar con archivos con extensión f4v ,por ejemplo en la serie la biblia y mucha gente no les puede reproducir en sus pcs
esta opcion ya la incluye la pagina http://www.filsh.net/ y creo que seria una muy buena opcion para mejorar y hacer crecer nuetra PyDownTV web.

¡¡ un saludo!!

**Comment by aabilio** [comment]
Es que esto es imposible para el servidor en el que estamos trabajando ahora. A parte, que trabajando en uno en el que nos lo pudiéramos permitir, esto causaría mucho consumo de recursos en el servidor, con lo que tendríamos que financiarnos de alguna manera para poder contratar planes más caros. Y cobrar por el servicio va contra las políticas de PyDownTV (http://www.pydowntv.com/legal).
Es cuestión de buscar otras maneras de atacar este problema para que todos estemos contentos.
De todas maneras, gracias por la sugerencia ;) Saludos.
