### ISSUE TITLE
Petición de nuevo canal: videos de ABC.es

### ISSUE THREAD

**Issue by MagoSolar** [aabilio/PyDownTV2#26]
El link del canal ABC.es:
http://www.abc.es/multimedia/index.asp

Agradezco.

**Comment by aabilio** [comment]
He añadido soporte para algunos vídeos, no sé en realidad cuántos están soportados (solo los que utilizan brightcove como cdn para los vídeos). Ejemplo: http://www.pydowntv.com/url/http://www.abc.es/videos-internacional/20130424/crimen-pasional-illinois-2324889522001.html (Lo malo es que son a través de rtmp:// :S)

**Comment by MagoSolar** [comment]
Intenté este link:
http://www.pydowntv.com/url/http://www.abc.es/videos-sociedad/20130402/metodos-escandinavo-waldorf-otra-2271253467001.html

y la respuesta fue:

C:\rtmpdump>rtmpdump -r 'rtmp://cp151415.edgefcs.net/ondemand/mp4/videos/5581426
0001/55814260001_2271873102001_M-todo-Escandinavo-y-Waldorf-la-otra-educacion-co
mpleto.mp4' -o 'VideoABC.mp4'
RTMPDump v2.1d
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
ERROR: Closing connection: NetStream.Play.StreamNotFound

C:\rtmpdump>

...o sea que no me va por ahora.

**Comment by MagoSolar** [comment]
Con otra versión del RTMPDump:

C:>rtmpdump -r 'rtmp://cp151415.edgefcs.net/ondemand/mp4/videos/55814260001/558
14260001_2271873102001_M-todo-Escandinavo-y-Waldorf-la-otra-educacion-completo.m
p4' -o 'VideoABC.mp4'
RTMPDump 2.4 git-b627335 2011-7-23
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
WARNING: Unknown protocol!

Connecting ...
INFO: Connected...
ERROR: Closing connection: NetStream.Play.StreamNotFound

C:>

**Comment by aabilio** [comment]
En un rato pruebo yo ese comando con mi versión a ver si me va

**Comment by aabilio** [comment]
Pues a mí los comandos que pegas me van con RTMPDUMP:
RTMPDump 2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL

Para Mac OS X..

**Comment by MagoSolar** [comment]
Curioso, ayer mismo usé el rtmpdump y funcionaba bien... no sé lo que va mal.

**Comment by denobisipsis** [comment]
Como comentaba en http://code.google.com/p/pydowntv/issues/detail?id=5#c23 (no sé si sigues los issues allí)

hay videos directos de descarga MP4. En el ejemplo que comentas http://www.abc.es/videos-internacional/20130424/crimen-pasional-illinois-2324889522001.html,

tienes http://comeresa.uds.ak.o.brightcove.com/78527749001/78527749001_2324881568001_130424AGEWEB-24AB050HQ.mp4

Estos enlaces se obtienen según el método descrito en el issue de pydown1 que comento.

**Comment by aabilio** [comment]
Sí, leo todo. Lo siento por tardar, pero más liado no puedo estar. Una empresa y varios proyectos que llevar.. Sorry. Espero tener un hueco a finales de semana. Si alguien quiere codificar bienvenido sea ;-) Graciñas a todos los que estáis activos esta semana (tanto en las issues del pydowntv2 como en pydowntv de Google Code. Saludos.

**Comment by denobisipsis** [comment]
Te echaría una mano, pero Python no sé, aunque todo puede llegar.

Un saludo y buen trabajo,

**Comment by MagoSolar** [comment]
Hoy me decidí a intentar de nuevo con el mismo link de hace meses y descubrí el fallo... en mis Windows XP o 7 la ruta deve estar entre comillas dobles (en lugar de simples), y el destino hay que ponerlo sin comillas. Funcionó perfecto y me quedó así:
C:\rtmpdump>rtmpdump -r "rtmp://cp151415.edgefcs.net/ondemand/mp4/videos/55814260001/55814260001_2271873102001_M-todo-Escandinavo-y-Waldorf-la-otra-educacion-completo.mp4" -o VideoABC.mp4

**Comment by denobisipsis** [comment]
Si coges el rtmp y cambias

rtmp://cp151415.edgefcs.net/ondemand/mp4/videos

por

http://comeresa.uds.ak.o.brightcove.com/

tienes un enlace directo

http://comeresa.uds.ak.o.brightcove.com/55814260001/55814260001_2271873102001_M-todo-Escandinavo-y-Waldorf-la-otra-educacion-completo.mp4
