### ISSUE TITLE
La Sexta Noche si, El Gran Debate de Tele5 no

### ISSUE THREAD

**Issue by quarter2013** [aabilio/PyDownTV2#27]
Hola zagales.

Como todos los domingos, me descargo con esta nuestra maravillosa web ambos programas que emitieron esta pasada madrugada para vermelos en la tele del dormitorio tranquilamente hasta que cierro los ojos y me echo la sagrada siesta usando el disco multimedia APPROX al que cargo su correspodiente memoria USB.

El tema es que los ficheros obtenidos .mp4 de la Sexta los reproduce perfectamente, y sin embargo el unico fichero obtenido .mp4 de Tele5 no me lo reproduce.

¿A que es debido? Quiero creer que formato generado del fichero .mp4 generado es diferente por codecs u otro tecnicismo que se me escapan como usuario.

La solucion inmediata es convertir por mi cuenta el fichero a otro que me reproduzca pero tarda horas y horas ya que son videos de varias horas (cuatro), y la otra es reproducirlo directamente en el monitor del PC sentado en el incomodo butacon.

Por todo, solo daros las gracias porque hasta que os decubri, los videos los descargaba de youtube. Pero debido a los copyright de un tiempo a esta parte ya no hay usuarios que los cuelguen integros.

MUCHAS GRACIAS Y BUENA INICIATIVA.

Saludos.

**Comment by aabilio** [comment]
No sé a qué puede ser debido ese comportamiento. Desgraciadamente desde PyDownTV no podemos hacer nada, ya que solo buscamos y mostramos el enlace final del vídeo, no podemos alojarlo ni tratarlo de ninguna manera ya que de esta manera estaríamos nosotros distribuyendo esos vídeos directamente...

Si encuentras alguna manera de solucionar este error que comentas sería interesante que expusieras aquí las conclusiones por si le puede ayudar a alguien.

Saludos.
