### ISSUE TITLE
Problema con un programa en mitele.es

### ISSUE THREAD

**Issue by mardojin** [aabilio/PyDownTV2#29]
Hola. Tengo problemas con el programa " Que hago yo aqui" de mitele en telecinco.
Cuando intento descargarlo me dice que no tengo autorizacion.

http://www.mitele.es/programas-tv/que-hago-yo-aqui/temporada-1/programa-1/

Gracias.

**Comment by aabilio** [comment]
Estás fuera de España? Yo es que lo puedo descargar perfectamente.

**Comment by mardojin** [comment]
Si. estoy fuera. Algunas veces tengo problemas por eso. Si no se puede pues nada tampoco es una emergencia. Simplemente queria preguntar.

Gracias.

**Comment by aabilio** [comment]
Si quires acceder a esos vídeos bloqueados tendrás que utilizar alguna herramienta extra (proxy, VPN, ...). Te dejo un enlace: http://blog.tvalacarta.info/2013/05/01/evitando-el-geobloqueo-los-metodos-mas-populares/

Saludos.

**Comment by mardojin** [comment]
Gracias. Lo intentare.

**Comment by mardojin** [comment]
De nuevo me prohiben descargar de mitele. Lo he estado haciendo sujetando "ALT" y el enlace al mismo tiempo. Eso me permitia descargarlo. Ahora nada. Me pone que no tengo autorizacion. Han vuelto a cambiar algo? 

Este es el video y me imagino que pasara igual con todo lo de mitele.

http://www.mitele.es/programas-tv/el-gran-debate/temporada-2013/programa-70/

Hay algo que pueda hacer. De aqui descargaba muchos programas para mi padre. Ya me han fastidiado.

Gracias.

Dolores.

**Comment by aabilio** [comment]
A mí solo me da problemas con ese vídeo, bien es cierto que he probado solo cinco o seis más. Es cuestión de ver qué está pasando cuando tenga un poco de tiempo. Saludos.

**Comment by mardojin** [comment]
Parece que han prohibido el gran debate. He probado algunos proxys pero no valen para nada.
