### ISSUE TITLE
No funciona rtmp mtv.es

### ISSUE THREAD

**Issue by dextertru** [aabilio/PyDownTV2#3]
No me funciona ningún enlace generado para rtmp en mtv.es, a ver si podéis dar con la solución, gracias por la pagina y un saludo.

**Comment by aabilio** [comment]
Es por problemas de geo boqueo (los servidores de PyDownTV están situados fuera de España), lo mismo me está pasando con Canal Historia. Tengo que encontrar un proxy español para rastrear los vídeos. Mañana si tengo un poco de tiempo lo arreglo.. Sorry.

**Comment by dextertru** [comment]
Muchas gracias por la rapidez, gran trabajo con la pagina un saludo y enhorabuena¡¡¡¡¡

**Comment by aabilio** [comment]
No me he olvidado ni de MTV ni de Canal Historia. Solo que no he encontrado un proxy fiable. Pero esta semana estará, estoy pendiente de activación de un hosting para una proyecto que estoy montando donde alojaré yo un proxy directamente. Así futuros problemas en este sentido estarán solucionados al momentos también.

Siento la tardanza. Saludos.

**Comment by aabilio** [comment]
Los problemas con mtv y Canal Historia deberían estar solucionados. Necesito confirmación ;)

**Comment by dextertru** [comment]
Excelente trabajo funciona a la perfección, lo he he probado y funciona todo bien, gracias por solucionarlo tan pronto,saludos¡¡¡¡

**Comment by frentemorao** [comment]
hola aabilio

He conocido tu web gracias a Jesús de tvalacarta y pelisalacarta. 
Este es mi primer post para decirte que a mi no me funciona ningún enlace generado para rtmp en mtv.es (he probado con Aragon TV para ver si era cosa del rtmp pero con Aragon TV funciona perfecto!!).

El error que me da la consola (windows XP) es: 
Error: Closing connection: netstream.play.streamnotfound

Gracias, un saludo

**Comment by aabilio** [comment]
Podrías poner un enlace concreto para probar? Yo acabo de probar con un par de vídeos de MTV y me ha funcionado con los dos (en Mac OS X Lion, y rtmpdump versión 2.4)

**Comment by frentemorao** [comment]
Pues por ejemplo: http://www.mtv.es/programas/destacados/geordie-shore-2/videos/geordie-shore-ep-208-parte-1-de-4-846388/

Este el código que se supone tengo que pegar en cmd: rtmpdump -r 'rtmpe://cp35019.edgefcs.net/ondemand/mtviestor/_!/intlod/es/tv/geordie-shore-2-temporada/gs-208_768x432_1700_m30.mp4' -o 'Geordie_Shore_Ep.208_Parte_1_de_4.mp4'

qué videos te han funcionado?? quizá podría probarlos yo también...

**Comment by aabilio** [comment]
![Captura de pantalla 2013-01-20 a la s 15 10 56](https://f.cloud.github.com/assets/664712/81249/56dcab88-630b-11e2-8885-61fb0a937e1a.png)

Como puedes ver en la captura de pantalla que adjunto a mi ese comando me va perfectamente.
Qué versión de rtmpdump estás usando, 2.4?

**Comment by frentemorao** [comment]
sí, uso la 2.4 pero pone rtmpdump 2.4 git-b627335 2001-7-23
![cmd](https://f.cloud.github.com/assets/3320661/81256/40348828-630c-11e2-8b2d-4a07ee3e1f44.JPG)

**Comment by aabilio** [comment]
Prueba esto (que puede ser una tontería pero por probar no se pierde nada): después de pegar el comando con las flechas de dirección posicionate sobre las comillas simples y edita las a mano,borrando la que está y oponiendo tú a mano las comillas simples desde tu teclado, a ver qué pasa.. ;-)

**Comment by frentemorao** [comment]
nada... no ha funcionado...
tendrá algo que ver el Unknown protocol??
o la versión de rtmpdump?? donde puedo descargar la tuya??

**Comment by aabilio** [comment]
Lo del protocolo puede que sea por que en esa versión de desarrollo que tienes no esté incorporado el soporte para rtmpE. Prueba esta: http://pydowntv.googlecode.com/files/rtmpdump-win32.zip No sé qué versión es, pero es la que tenía en descargas para la versión primera de pydowntv para Windows (es la que tengo enlazada en la sección de ayuda de pydowntv)

**Comment by frentemorao** [comment]
esa misma es la que había descargado (la enlazada)... puede que haya alguna diferencia entre la de windows y la de Mac???

**Comment by aabilio** [comment]
No creo que sea el SO. Me decanto mas por la versión. El problema es que en la web oficial no reparten binarios para la 2.4, solo dan el código para que lo compiles tú. He buscado en google a ver si alguien había compilado alguna 2.4 más moderna que la que tú tienes y entre otras cosas me ha salido esto: http://m.general-files.com/download/rtmpdump (el segundo resultado, es una 2.4 mas actual, por la fecha, pero claro, no tengo ni idea su procedencia y por supuesto, no me hago responsable de cualquier error que ese ejecutable pueda provocar en tú SO ;-) )

**Comment by frentemorao** [comment]
la he descargado pero no veo ningun .dll
he copiado el rtmpdump.exe sin exito... me sigue dando el mismo error

qué videos de mtv sí te funcionan a ti??

**Comment by aabilio** [comment]
Pues he probado con los últimos de Gandia Shore, ejemplo..

**Comment by frentemorao** [comment]
nada... sin exito...

**Comment by aabilio** [comment]
Con la otra versión también te salía el mismo error? Estas intentando descargar el vídeo desde una IP española o te encuentras fuera de España?

**Comment by frentemorao** [comment]
he probado con varias versiones y en todas el mismo error...
intento descargar el video desde IP española (también puedo ver bien el video en la web de mtv...)

**Comment by aabilio** [comment]
Pues no tengo ni idea de por qué.. Es un problema mas especifico de rtmpdump tanque a mí me descargan bien los vídeos. Buscaría por foros específicos y trataría de obtener la versión mas reciente de rtmpdump que pudiera. No sé qué más probar..

**Comment by Edu1980** [comment]
Buenas, pues a mi también me daba el  "Error: Closing connection: netstream.play.streamnotfound", pero encontré como solucionarlo.

Versión rtmpdump: 2.4 git-b627335
Sistema operativo: Windows 7 x64

El script web me tira este enlace:

rtmpdump -r 'rtmpe://cp35019.edgefcs.net/ondemand/mtviestor/_!/intlod/es/tv/catfish/catfish-101_768x432_1700_m30.mp4' -o 'Catfish_Ep.101_Parte_1_de_4.mp4'

Como se ve, el enlace rtmp está envuelto con estas comillas ('), al cambiarlas por las comillas normales (") funciona perfecto :)

El enlace quedaría así:

rtmpdump -r "rtmpe://cp35019.edgefcs.net/ondemand/mtviestor/_!/intlod/es/tv/catfish/catfish-101_768x432_1700_m30.mp4" -o Catfish_Ep.101_Parte_1_de_4.mp4

Si tenéis problemas, probad de ese modo.

Saludos!

**Comment by aabilio** [comment]
@Edu1980 gracias ;)

**Comment by ghost** [comment]
A ver la verdad es que  mi uso la ultima version de mac pero la web da error.

http://intl.esperanto.mtvi.com/www/custom/intl/errorslates/copyright_error.flv?geo%3Dus' -o 'Geordie_Shore_Ep.704.mp4'

lo ves, ?? como lo arrglo ?
