### ISSUE TITLE
Ya no se puede Descargar de EITB

### ISSUE THREAD

**Issue by ghost** [aabilio/PyDownTV2#30]
Han cambiado algo en la web de http://www.eitb.tv/es/ y ahora es imposible descargar los videos de alacarta. ¿Alguna sugerencia?

**Comment by aabilio** [comment]
Tengo que echarle un ojo a ver qué está pasando..

**Comment by aitorarber** [comment]
De todas formas, eres un crack. :)
Dale a ver si investigas porque necesito unos cuántos videos de EITB para mis clases...

**Comment by aabilio** [comment]
Si el problema es que no tengo tiempo, pero espero poder este fin de semana ;)

**Comment by aabilio** [comment]
Ya tengo la solución. A ver di me a tiempo a subirla mañana. Saludos.

**Comment by ghost** [comment]
A quien les estas diciendo eso?. Como yo abrí este hilo igual es a mi. Saludos.

**Comment by aabilio** [comment]
EITB a la carta debería de funcionar bien ya otra vez. (http://www.pydowntv.com/url/http://www.eitb.tv/es/video/de-boca-en-boca-lo-+-visto/594281726001/2379140153001/de-boca-en-boca-el-gran-crack-espanol-/)
