### ISSUE TITLE
Videos de EITB.TV

### ISSUE THREAD

**Issue by aitorarber** [aabilio/PyDownTV2#33]
Estuve tratando de ver en el código html que tienen las páginas de los videos, pero nada. Al pegar la dirección en "introduce la url del video a descargar" sale otra página de error, diciendo que la url no existe o no está disponible.

**Comment by ghost** [comment]
Si dispones de windows puedes usar el programa este para mirar su código. http://www.streamtransport.com/

**Comment by aabilio** [comment]
#30
