### ISSUE TITLE
mitele.es ha dejado de funcionar

### ISSUE THREAD

**Issue by simonbcn** [aabilio/PyDownTV2#34]
Lo que intento bajar es el vídeo del debate de GH: http://www.mitele.es/programas-tv/gran-hermano/gh-14/el-debate-13/
Lo he intentado con Google Chrome v26.0.1410.63 y Firefox 21 y en los dos falla.

En el caso de Google Chrome cuando selecciono "Guardar enlace como..." no hace nada.
En el caso de Firefox me baja un HTML en lugar del vídeo y el contenido del HTML es:

```
 Authorization Required
 This server could not verify that you are authorized to access the document you requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.
```

**Comment by aabilio** [comment]
Parece que algunos vídeos de mitele están empezando a dar problemas. Le echaré un vistazo en cuanto tenga tiempo..

**Comment by simonbcn** [comment]
Estoy bajando el programa de GH de este jueves y aunque la descarga comienza bien se corta a los pocos minutos de empezar.

**Comment by aabilio** [comment]
¿Con el script o a través de la web? ¿Utilizas algún gestor de descargas o simplemente a través del propio navegador? ¿Te ha pasado algo similar con algún otro vídeo o es un caso aislado?
¿Me puedes pasar el enlace exacto del problema?

**Comment by simonbcn** [comment]
Por fin, a la tercera va la vencida y ya ha bajado.
Uso la extensión de Chrome.
