### ISSUE TITLE
disney channel replay

### ISSUE THREAD

**Issue by aabilio** [aabilio/PyDownTV2#37]
Alguien pidió por Facebook soporte para disney channel replay. Lo dejo aquí para el futuro...

**Comment by aabilio** [comment]
:+1: 
Merged (y añadido a la web también: https://github.com/aabilio/PyDownTV2/commit/0676d3ccb2ccb1bc6b6b15e8234e063152b96dd2).
Graciñas.

**Comment by aabilio** [comment]
Parece que en algunos vídeos duplica la misma url (para la descarga), ¿no?

**Comment by jaimeMF** [comment]
¿Tienes algún ejemplo?

**Comment by aabilio** [comment]
--> http://replay.disneychannel.es/jake-y-los-piratas-de-nunca-jamas/la-roca-de-la-ronda.html
[...]/PyDownTV2/Script/pydowntv.py -nsd "http://replay.disneychannel.es/jake-y-los-piratas-de-nunca-jamas/la-roca-de-la-ronda.html"

En Web: http://www.pydowntv.com/url/http://replay.disneychannel.es/jake-y-los-piratas-de-nunca-jamas/la-roca-de-la-ronda.html

**Comment by antonio8909** [comment]
yo ya sabia desde hace 3 meses la manera de descargar de disney channel replay

**Comment by jorgemitcom** [comment]
Chicos, acaban de cambiar el metodo para los nuevos capitulos como este:http://replay.disneychannel.es/yo-no-he-sido/el-perro-de-la-casa-blanca.html
Hay algunos que siguen conservando el antiguo metodo, pero los que van colgando nuevos, al xml del episodio hay que añadirle "_mobile", y viene el capitulo todo junto, no por partes

**Comment by denobisipsis** [comment]
http://i3tv.dcres.edgesuite.net/assets2/2014/08/28/00001/video_720_900k_es.mp4

Utiliza NetStorage y archivoNetStorage del xml (os suena de algo ese tipo
de enlaces? :))

**Comment by jorgemitcom** [comment]
A mi no, pero recomendaría cambiar lo más pronto el sistema, y que solo coger el de <videoEsHigh>, porque es el que está en castellano y en alta calidad. Recuerdo que está disponible para todos los episodios, no tiene limitación, ya que de ahí cogen los enlaces la aplicación para Android.

**Comment by antonio8909** [comment]
@denobis como puedo contactar contigo por mail? Te tengo una pregunta sobre un servicio

**Comment by denobisipsis** [comment]
froheweihnachten2014@gmail.com

2014-09-10 23:35 GMT+02:00 antonio8909 notifications@github.com:
