### ISSUE TITLE
Continuar descarga

### ISSUE THREAD

**Issue by rkmax** [aabilio/PyDownTV2#39]
Es posible continuar una descarga.

He construido un pequeño script con python que hace uso de APi de PyDownTV funciona de maravilla con mitele.es pero me gustaria implementar que las descargas se puedan reanudar.

pienso que esto es posible de implementar ya que el reproductor de mitele.es permite adelantar el progreso del capitulo

analizando la URL que devuelve para descargar el archivo, Ej,

```
http://videosgeo.mitele.es/geo/seriesonline/aida/t1/c11.mp4?vf=20130529160340&vu=20130529160348&h=0cd80103e36b388690738&start=0
...
?vf=20130529160340&vu=20130529160348&h=0cd80103e36b388690738&start=0
```

al final muestra un valor de inicio pero no se si este valor son segundos o bytes

**Comment by aabilio** [comment]
Lo primero, por si acaso te interesa, el proyecto de PyDownTV actualmente dispone de un script en python para terminal: https://github.com/aabilio/PyDownTV2/tree/master/Script por si te interesaría trabajar en este en vez de crear uno nuevo.

Sobre lo que comentas, el valor de start, según he podido ver jugando un poco con él, representa los segundos (empezará a reproducir el vídeo desde el segundo que se pase a start, marcando este segundo como 0 en el reproductor).

A título personal sin embargo, te recomendaría que implementases la pausa y reanudación de los vídeos directamente calculando los bytes descargados y el total del recurso (por ejemplo con la cabecera Content-Length (Ref.: http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html - Sec: 14.13) bien sea "inline" o guardando alguna información sobre la descarga en un fichero auxiliar temporal (tamaño total, descargado, estado de la descarga).

Saludos.
