### ISSUE TITLE
Ahora si que no me funciona mitele.es (a alguien más le pasa?)

### ISSUE THREAD

**Issue by deivipsp21** [aabilio/PyDownTV2#4]
Hola, antes de la actualizacion me podía descargar los vídeos de mitele, algunas veces me daba problemas pero lo intentava 3 o 4 veces y al final podía. ahora es que no consigo, y lo e intentado un montón de veces y rápido como dice el tutorial de ayuda. Solución por favor. gracias

**Comment by aabilio** [comment]
La verdad es que a mí me va muy bien, incluso esperando el tiempo que quiera para descargarme el vídeo.. No sé por qué te fallará a tí. A ver si a alguien más le pasa..

**Comment by aabilio** [comment]
@deivipsp21 continúas con este error?

**Comment by deivipsp21** [comment]
Gracias por preocuparte, pero desde a actualización no he conseguido bajarme ningún vídeo, y no será por intertarlo

soy david

**Comment by aabilio** [comment]
Es que es rarísimo, eres el único que me ha reportado este error.. No sé a qué se debe.,

**Comment by deivipsp21** [comment]
de nuevo muchas gracias por preocuparte. Lo volvi a intentar, y no conseguia que descargara el video, pero claro, yo le estaba dando al enlace como la anterior version de pydowtv, no al titulo del video que me quiero descargar, que aparece un poco mas abajo en azul y subrayado. Por fin ya puedo descargar y sin problema (por lo menos el primer video). Muchas gracias.

Date: Mon, 28 Jan 2013 16:58:06 -0800
