### ISSUE TITLE
No se pueden descargar videos de MiTele

### ISSUE THREAD

**Issue by ghost** [aabilio/PyDownTV2#48]
Desde hace apenas unas horas al intentar descargar cualquier video de MiTele, me aparece este mensaje:

ERROR al recuperar el vídeo: mitele.es: No funciona el procedimiento

Puede algo que ver con el anuncio que se reproduce antes del video? Si le puedes echar un vistazo, sería perfecto.

Gracias de antemano

PD: Por cierto, fantástica utilidad. Muchas gracias por compartirla con todos.

**Comment by aabilio** [comment]
Tengo que verlo. Hasta mañana por la tarde no podré.. 
Gracias por reportar. 
Saludos.

**Comment by aabilio** [comment]
He podido comprobar que es debido a otro bloqueo más por parte de mitele a pydowntv.

**Comment by ghost** [comment]
Vamos, que están constantemente poniendo trabas a PyDownTV los de mitele.
Si encuentras la manera de poder descargar los videos, perfecto. Si no, pues no pasa nada

Gracias por tu tiempo

**Comment by aabilio** [comment]
Solucionado, o debería.
Saludos.

**Comment by ghost** [comment]
Muchísimas gracias.

Eres un crack
