### ISSUE TITLE
Soporte MiteleKids

### ISSUE THREAD

**Issue by antonio8909** [aabilio/PyDownTV2#49]
Pido soporte si es posible para el nuevo MiteleKids (url de ejemplo:http://www.mitelekids.es/castellano/series-infantiles/berni/temporadas/1/Golf_23_1637295001.html)
Un saludo

**Comment by aabilio** [comment]
Añadido. Saludos. Ejemplo: http://pydowntv.com/url/http://www.mitelekids.es/castellano/series-infantiles/berni/temporadas/1/Golf_23_1637295001.html

**Comment by antonio8909** [comment]
Otra página ya se os ha adelantado pero muchísimas gracias!

**Comment by aabilio** [comment]
Perfecto! Cuantos más mejor. Saludos.

**Comment by antonio8909** [comment]
Gracias!
