### ISSUE TITLE
El plugin para chrome no detecta bien la url desde la que se ejecuta

### ISSUE THREAD

**Issue by cur3n79** [aabilio/PyDownTV2#5]
Desde la última actualización del plugin si se tiene al menos 2 ventanas de chrome abiertas al pulsar el botón del plugin desde la segunda la url que le pasa a la página es la que esta abierta en la primera ventana.
No es muy importante, pero puede llevar a engaños a alguien inexperto.

**Comment by aabilio** [comment]
Conocía ya este bug, pero muchas gracias por reportar. A ver si lo puedo corregir pronto. Saludos ;)

**Comment by aabilio** [comment]
La actualización ya está subida al repositorio de plugins de Google Chrome (https://chrome.google.com/webstore/detail/pydowntv/ljbpalaakngapgpfkidnohfokabnkiof/details).
Esperando a que se actualice en los servidores, la versión que debería corregir el problema es la 3.0.5 (por ahora aun se encuentra en la 3.0.1).
Google Chrome actualizará automaticamente el plugin supongo ;)

Supongo que funcionará bien, pero si notáis algún comportamiento inesperado comunicádmelo, por favor.

Gracias. Saludos!

**Comment by aabilio** [comment]
Ya está disponible la actualización en: https://chrome.google.com/webstore/detail/pydowntv/ljbpalaakngapgpfkidnohfokabnkiof

**Comment by cur3n79** [comment]
Funciona perfectamente muchas gracias y enhorabuena de nuevo por el proyecto.
