### ISSUE TITLE
Los vídeos de cuatro (al menos los de TikiTaka) no se descargan

### ISSUE THREAD

**Issue by vikenbauer** [aabilio/PyDownTV2#53]
Ejemplo: http://www.cuatro.com/tiki-taka/a-carta/Tiki-Taka_2_1655880019.html

Dice "Error al recuperar el vídeo:cuatro.com:no se encuentra contenido.
Lo estoy probando con Chrome y el plugin. También lo probé escribiendo directamente la url en http://www.pydowntv.com/, y tampoco.

De todos modos, enhorabuena, habéis tenido una idea genial.

**Comment by denobisipsis** [comment]
Será un error al obtener la id, puede variar según las páginas,

http://storage.telecinco.es/nogeo/2013/08/21/MDSVID20130821_0019-0.mp4?vf=20130821094919&vu=20130822094919&h=0466ee0caa344b97f42f0

**Comment by vikenbauer** [comment]
Con esta url tampoco lo consigo. No sé muy bien como funciona esto, ¿es una
url de un solo uso?
  Víctor

2013/8/21 denobis notifications@github.com

**Comment by denobisipsis** [comment]
Botón derecho del ratón y guardar enlace como

**Comment by aabilio** [comment]
Era el mismo problema que el del otro día con T5, por eso ya está solucionado. Gracias por reportar. Saludos.
http://www.pydowntv.com/url/http://www.cuatro.com/tiki-taka/a-carta/Tiki-Taka_2_1655880019.html

**Comment by vikenbauer** [comment]
Esto es del primer capítulo de "Internet para dummies" :D En fin, corramos
un tupido velo, y muchas gracias :)
  Víctor
