### ISSUE TITLE
¿La branch master es la última versión?

### ISSUE THREAD

**Issue by spain-shoemaker** [aabilio/PyDownTV2#54]
Hola,

¿La branch master es la última versión correspondiente a la Web? Si lo es no acabo de entender cómo en la web me puedo descargar el siguiente vídeo:

http://www.telecinco.es/fragiles/temporadas/temporada-02/t02xc05-el-deportista-atropellado/T02xC05-deportista-atropellado_2_1654830129.html

No obstante si lo ejecuto desde el Script de python me da el siguiente error:

$ git clone https://github.com/aabilio/PyDownTV2.git
$ cd PyDownTV2/Script/
$ ./pydowntv.py 
## PyDownTV (Descarga vídeos de las webs de TV españolas):

[--->] Introduce las URL de los vídeos (separadas por espacios): 
http://www.telecinco.es/fragiles/temporadas/temporada-02/t02xc05-el-deportista-atropellado/T02xC05-deportista-atropellado_2_1654830129.html

[ URL ] http://www.telecinco.es/fragiles/temporadas/temporada-02/t02xc05-el-deportista-atropellado/T02xC05-deportista-atropellado_2_1654830129.html 
[INFO] Telecinco.es 
Traceback (most recent call last):
  File "./pydowntv.py", line 203, in <module>
    info = canal.getInfo()
  File "/tmp/PyDownTV2/PyDownTV2/Script/spaintvs/telecinco.py", line 138, in getInfo
    if name != None:
UnboundLocalError: local variable 'name' referenced before assignment

Me da la sensación que los scripts de spaintvs no está actualizados.

Gracias anticipadas.

**Comment by aabilio** [comment]
Nop, no subí los últimos cambios. Ahora hago un push ;)

**Comment by aabilio** [comment]
Ya: https://github.com/aabilio/PyDownTV2/commit/3b71e0da50e00f497ca0786f1c9c53ff2f750fc1 ;)
T5: https://github.com/aabilio/PyDownTV2/blob/3b71e0da50e00f497ca0786f1c9c53ff2f750fc1/spaintvs/telecinco.py

Saludos.
