### ISSUE TITLE
Mitele.es ha dejado de funcionar otra vez

### ISSUE THREAD

**Issue by simonbcn** [aabilio/PyDownTV2#55]
Intento descargar este programa: http://www.pydowntv.com/?url=http%3A//www.mitele.es/programas-tv/me-cambio-de-familia/temporada-3/programa-29/ y me baja un html, en lugar del MP4, con este error:

> Authorization Required
> This server could not verify that you are authorized to access the document you requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

**Comment by aabilio** [comment]
He probado un par de vídeos más a parte de ese y parece que no dan problemas. No sé qué puede estar pasando con ese. Cuando tenga tiempo le echo un ojo. Gracias por reportar. Saludos.

**Comment by denobisipsis** [comment]
http://videosgeo.telecinco.es/geo/programa/mecambiodefamilia/t3/c29ok2_1f6f3332.mp4?vf=20130828130421&vu=20130828150421&h=01131ac888e54ee2598bc&start=0

El fallo está en el propio xml de mitele

["link"]=>
        string(55) "/geo/programa/mecambiodefamilia/t3/c29ok2_1f6f3332.mp4 " (espacio al final)

**Comment by aabilio** [comment]
Thanks Denobis ;)
He corregido eso, pero al ver si funcionaba, me da un 401... En fin, si no son muchos más vídeos lo apunto para más adelante.

**Comment by denobisipsis** [comment]
Quita simplemente los espacios vacíos del link, en php lo hago con
str_replace(" ","",$link). A mí me funciona, lo que pasa es que el
link caduca, aquí está de nuevo

http://videosgeo.telecinco.es/geo/programa/mecambiodefamilia/t3/c29ok2_1f6f3332.mp4?vf=20130828185016&vu=20130828205016&h=0caafa61d2d2fb89cef7d&start=0

**Comment by aabilio** [comment]
Sí, si el error que me comentabas al principio lo hice de la misma manera que tú .replace(" ", ""): https://github.com/aabilio/PyDownTV2/commit/524addbbc3120c2ca9b6cd37fd3aab76e87f7530

Pero el resultante me da un 401, incluso al instante, solo con ese vídeo (si fuera con todos ya pensaría que están bloqueado por 1233423523412 pydowntv de alguna manera), con otros sigue funcionando bien...

Además, he visto que el enlace que proporcionas dura una barbaridad comparado con lo que me duran a mí para el resto en el que sí funciona...

**Comment by denobisipsis** [comment]
Prueba con "User-Agent: iPod|iPad|android"

**Comment by aabilio** [comment]
Para hacer la petición al tokenizer supongo ¿no?
OK, luego en un ratito pruebo y te digo. Graciñas ;)

**Comment by denobisipsis** [comment]
Sí, la llamada con el hash, id, startime y endtime

**Comment by aabilio** [comment]
@denobis Sí, con ese User-Agent dura más :+1: Muchas gracias.
PD: Siento tardar tanto. Aun he podido probarlo ahora...

**Comment by aabilio** [comment]
https://github.com/aabilio/PyDownTV2/commit/06823154885ef479c7fa8de4ba24d057bde14bff
