### ISSUE TITLE
no se si se podra solucionar esto

### ISSUE THREAD

**Issue by kiraaaaaa** [aabilio/PyDownTV2#59]
http://www.mitele.es/series-online/el-don-de-alba/temporada-1/capitulo-13/

no coje ningun capitulo de el don de alba da un error

**Comment by aabilio** [comment]
Esa serie, MiTele la pone a disposición de la audiencia a través de un protocolo llamado RTMP. Los vídeos que mitele dispone a través de este protocolo no están soportados aun por Pydowntv. En un futuro los podrás reconocer por que el mensaje de error proporcionado por Pydowntv es precisamente este que estoy diciendo. 

Ahora mismo no estoy trabajando en una solución, pero no lo descargo para cuando tenga tiempo. 

Saludos.
