### ISSUE TITLE
MiPony

### ISSUE THREAD

**Issue by Begas** [aabilio/PyDownTV2#6]
Me gustaría...

...que se adaptara a MiPony, como ya lo hace (supuestamente, porque no lo he probado) con JDownloader.

Mil gracias!!!

**Comment by aabilio** [comment]
En cuanto tenga un poco de tiempo veré qué se puede hacer ;-)

**Comment by Begas** [comment]
Muchas gracias!!!

Lo utilizo bastante para bajarme series de TVE y Antena3, pero utilizo el
MiPony.

**Comment by aabilio** [comment]
Ya me he puesto en contacto con el desarrollador de Miponi para ver si su software dispone de alguna manera de integrar enlaces de terceros desde una web. Esperando respuesta ;)

**Comment by aabilio** [comment]
Continuo esperando respuesta del creador de Mipony..
