### ISSUE TITLE
Si puedo descargar casi todo............

### ISSUE THREAD

**Issue by mardojin** [aabilio/PyDownTV2#65]
Quería añadir algo.  He estado haciendo pruebas, y resulta que yo puedo descargar todo perfectamente. 

Siempre he utilizado IDM, (Internet Download Manager) para descargar todo. Es muy rápido y muy bueno.  Yo nunca he utilizado el método de hacer cliq y escoger "guardar como....."

En mi caso, después de obtener el enlace con pydown, al hacer cliq, salta IDM para ofrecer el descargo. Entonces  he estado probando descargar los programas que suelo descargar siempre, (algunos son de antena3, otros de la sexta y otros de Nova). 

Resulta que todos descargan sin ningún problema. Son las TELENOVELAS las que no dejan descargar. Ni siquiera con  IDM es posible. Eso es lo que  yo no puedo resolver. Creo que tendrá algo que ver con ser telenovelas de México.  Tiene que ver algo con eso, estoy segura porque todo lo demás lo descargo. He tardado hasta que me he dado cuenta de que el cambio no me afecta. Son las telenovelas las que no puedo conseguir.
Hay solución para esto?

Gracias.

**Comment by aabilio** [comment]
No sé cuál puede ser el problema la verdad. Supongo que estarán más protegidos al ser una producción extrajera..
