### ISSUE TITLE
Api problema espacios (atresplayer) bug

### ISSUE THREAD

**Issue by peter55** [aabilio/PyDownTV2#68]
Hola, gracias por la rapidez en soportar atresplayer.

Quería comentar que las urls de atresplayer que contienen espacios en la api no funcionan correctamente y en la versión web si.

Por ejemplo:
http://www.atresplayer.com/television/programas/karlos-argui%C3%B1ano-en-tu-cocina/temporada-1/Karlos%20Argui%C3%B1ano%20en%20tu%20cocina-C27_2013092700194.html
Gracias.
Saludos.

**Comment by aabilio** [comment]
si puedo mañana le echo un ojo. Gracias por reportar.

**Comment by aabilio** [comment]
Puedes poner la url sin "http://" si utilizas la forma "restfuliana" en: http://www.pydowntv.com/api/www.atresplayer.com/television/programas/karlos-argui%C3%B1ano-en-tu-cocina/temporada-1/Karlos%20Argui%C3%B1ano%20en%20tu%20cocina-C27_2013092700194.html

o utilizar la forma: http://www.pydowntv.com/api?url=http://www.atresplayer.com/television/programas/karlos-argui%C3%B1ano-en-tu-cocina/temporada-1/Karlos%20Argui%C3%B1ano%20en%20tu%20cocina-C27_2013092700194.html

De esas dos maneras ya debería ir ;)

Saludos y gracias por reportar.
