### ISSUE TITLE
Problema con atresmedia

### ISSUE THREAD

**Issue by susobaco** [aabilio/PyDownTV2#69]
Hola...Gracias por el pronto soporte...creo que queda algún flequillo que pulir...en el programa de "el objetivo":

http://www.atresplayer.com/television/programas/el-objetivo/temporada-2/capitulo-6-vicente-martnez-pujalte_2013100600191.html

El error es el siguiente:

ERROR al recuperar el vídeo. ¿Es una URL válida? Expecting , delimiter: line 1 column 1055 (char 1054) 

Muchas gracias!

**Comment by aabilio** [comment]
Debería estar arreglado ya este error: http://pydowntv.com/url/http://www.atresplayer.com/television/programas/el-objetivo/temporada-2/capitulo-6-vicente-martnez-pujalte_2013100600191.html
