### ISSUE TITLE
BBC One y demás familia

### ISSUE THREAD

**Issue by mmon** [aabilio/PyDownTV2#7]
Hola,
de antemano muchas felicidades por este gran trabajo y compartirlo con los usuarios que nos liamos con mas de dos lineas de comando ;)
Queria proponer todos los canales que tiene BBC y no podemos verlos online por causa de la IP.
Gracias por todo y mucho animo para seguir adelante con este proyecto que ya es una realidad.

mmon

**Comment by aabilio** [comment]
No te voy a engañar, ahora mismo tengo muchos proyectos en marcha y les estoy dando prioridades distintas. Debido a que PyDownTV nació como soporte a las televisiones españolas, incluir BBC no es un prioridad ahora mismo, aunque no se descarta para un futuro.

De todas maneras, PyDownTV y spaintvs son Software Libre, y cualquiera puede hacer un fork del proyecto y continuarlo si quiere, como si por el contrario quiere participar conmigo en este. Cualquiera puede dar soporte a nuevos canales (como ejemplo para empezar, se tiene: https://github.com/aabilio/PyDownTV2/blob/master/spaintvs/ejemplo.py).

Por otro lado, por parte de PyDownTV dar soporte a contenidos bloqueados por las cadenas, no es su prioridad (ya sea por que estas no quieres disponer sus vídeos fuera de sus fronteras, o por que sean contenidos de pago). Es por eso que tampoco se da soporte para los vídeos Premium de algunas cadenas aunque se tenga conocimiento de cómo acceder a ellos.

Saludos.
