### ISSUE TITLE
Han bloqueado otra

### ISSUE THREAD

**Issue by mardojin** [aabilio/PyDownTV2#71]
Siento tener que molestarle otra vez.  Creía que estaba todo solucionado pero no entiendo esta gente que están haciendo.  Resulta que la otra novela, la que no tenia problema para descargar, ahora no puedo. La que me soluciono si la puedo descargar pero esta otra, que he estado descargando sin ningún problema desde que cambiaron al sistema este de atresplayer, hoy de repente voy a descargar el próximo capítulo y no puedo. No lo entiendo. Si le es mucho trabajo no se preocupe. ¡Estos cambios me vuelven loca!

El enlace:

http://www.atresplayer.com/television/series/angel-rebelde/temporada-1/capitulo-104-8-10-13_2013100800189.html

**Comment by LuCoSiN** [comment]
A mi me pasa lo mismo con la novela el clon http://www.atresplayer.com/television/series/el-clon/temporada-1/capitulo-173-3-10-13_2013100700327.html

Dice: ERROR al recuperar el vídeo. ¿Es una URL válida? HTTP Error 401: Unauthorized 

Gracias!

**Comment by LuCoSiN** [comment]
Vale, ya pide descarga rel capítulo 173, pero el 174 http://www.atresplayer.com/television/series/el-clon/temporada-1/capitulo-174-4-10-13_2013100700247.html salen los links de todas las calidades pero el archivo que se baja es de bytes. ¿Porqué no está disponible ninguna calidad?

Gracias!
