### ISSUE TITLE
Atresplayer: ¿están subidos los últimos cambios al repositorio?

### ISSUE THREAD

**Issue by spain-shoemaker** [aabilio/PyDownTV2#76]
Buenos días,

He observado que desde la versión web es posible obtener los vídeos de urls como ésta:

http://www.atresplayer.com/television/series/vive-cantando/temporada-1/capitulo-6-captulo_2013100400464.html

No obstante me he bajado la última versión que hay subida en GitHub y cuando pruebo la versión script no me funciona:

$ pydowntv.py 
## PyDownTV (Descarga vídeos de las webs de TV españolas):

[--->] Introduce las URL de los vídeos (separadas por espacios): 
http://www.atresplayer.com/television/series/vive-cantando/temporada-1/capitulo-6-captulo_2013100400464.html

[ URL ] http://www.atresplayer.com/television/series/vive-cantando/temporada-1/capitulo-6-captulo_2013100400464.html 
ERROR: La URL "http://www.atresplayer.com/television/series/vive-cantando/temporada-1/capitulo-6-captulo_2013100400464.html" no pertenece a ninguna Televisión soportada

¿Es posible que no estén subido todos los cambios al repositorio?

Por otro lado, he visto que comentabais que el sessionId se calculaba concatenando sessionId=contentPk|time|hash donde hash sirve cualquier número - aunque la norma general es el userId-. ¿Es realmente así? Cuando pruebo a generar urls

https://servicios.atresplayer.com/api/urlVideoLanguage/20131004-EPISODE-00022-false/web/20131004-EPISODE-00022-false%7C1381822013%7C1324d78efc1fb0e1dce96eddffb3a87e/es.xml

Siempre me devuelve "Hash no válido". ¿Cómo se calcula el hash?

Aprovecho la ocasión para agradecerte todo el trabajo y tiempo que dedicas desinteresadamente.

**Comment by aabilio** [comment]
Los enlaces que da pydowntv ahora mismo no son válidos.
Esto aun así, aun no está subido al repositorio. Tardará un poco.
Saludos.

**Comment by sergioabril** [comment]
Eso venía a comentar, que los enlaces que da no son validos; hay intención o previsión de que se consigan videos válidos desde atresplayer.com?

**Comment by aabilio** [comment]
Ahora los cambios están subidos al servidor.
Pero la API (y por lo tanto el script) solo funcionará para los vídeos FREE, no lo REGISTER.. (Para estos últimos da un enlace a la API de atresplayer que dará el enlace final)..
