### ISSUE TITLE
Antena3 Y Telecinco

### ISSUE THREAD

**Issue by TOINUSA** [aabilio/PyDownTV2#77]
Hola,
Supongo que ya habreis tenido varios comentarios sobre el "atres player" you no puedo ver nada desde el lunes (estoy en Estados Unidos). Querria saber si se va a arreglar porque me encanta Pydown, es muchisimo mejor que el atres ese. Tampoco puedo ver "Tierra de Lobos" y cuando echaron "Reserva" en RTVE tampoco se veia. Bueno en fin espero que lo podais solucionar. Yo no soy programadora o nada de eso, pero si os puedo ayudar en algo decirmelo.

**Comment by aabilio** [comment]
#61 #80
