### ISSUE TITLE
Se soportará Telecinco.es en la API?

### ISSUE THREAD

**Issue by iptvwebtv** [aabilio/PyDownTV2#8]
Hola, me gustaría saber si tenéis previsto dar soporte a Telecinco.es en la API para una posible aplicación. Veo que Mitele.es si que funciona, pero no los videos con dirección telecinco.es. Muchas gracias

**Comment by aabilio** [comment]
Sí que hay soporte para telecinco.es si no funciona es que debe estar fallando. Mañana le echo un ojo..

**Comment by iptvwebtv** [comment]
Ok, gracias por la atención tan rápida. Pensaba que la API no soportaba todos los que soporta la versión web al ver que los enlaces de Telecinco.es si que los saca esta pero la API no.

**Comment by aabilio** [comment]
No es que la API de spaintvs soporte todos los canales de PyDownTV2, sino que PyDownTV2 utiliza al mismo tiempo la API directamente (forman parte del mismo proyecto, son lo mismo ;))

El problema con Telecinco.es era muy raro, utilizando directamente spaintvs sobre PyDownTV2 obtenía unos datos diferentes que si lo hacía la vista que maneja las peticiones a la API.

Ahora mismo parece estar solucionado, clonando las dos vistas... En fin, no sé ni por qué pasaba ni por que ahora supuestamente funciona bien, pero parece que va.. (http://web.pydowntv.com/api?url=http://www.telecinco.es/elgrandebate/2013/enero/26-01-2013/Gurtel-Luis_Barcenas-Mariano_Rajoy-Soraya_Saenz_de_Santamaria-Maria_Dolores_de_Cospedal-PP-Corrupcion-Sobresueldos-Suiza_2_1547730006.html)

Saludos!

**Comment by iptvwebtv** [comment]
Entendido :)

Si, ahora funciona perfectamente. Muchas gracias de nuevo :)
