### ISSUE TITLE
Nueva issue sobre mitele.es

### ISSUE THREAD

**Issue by antonio8909** [aabilio/PyDownTV2#82]
Dado que han cerrado el otro tema informo que sigue sin funcionar.
La página devuelve esto: ERROR al recuperar el vídeo: mitele.es: RTMP no soportado para el canal por ahora.
Por favor echadle un vistazo.
Gracias

**Comment by aabilio** [comment]
Los vídeos que dicen eso es por que MiTele los dispone a través de ese protocolo y nunca han sido soportados por pydowntv. No sé si lo estará alguna vez, pero no de momento. Saludos.
