### ISSUE TITLE
Nombre del fichero destino como parámetro

### ISSUE THREAD

**Issue by JorgeGlez** [aabilio/PyDownTV2#84]
Buenas,

Escribo aquí por primera vez así que perdona si no es el sitio correcto o algo.

Estaba probando tu script (que dicho sea de paso es la leche, enhorabuena) y ví que me descargaba los videos con nombre destino "V". Indagando un poco he visto que si no saca bien el nombre (al menos para los de Telecinco) le asigna el nombre genérico "VideosDeTelecinco.mp4" y al final le pasa sólo el primer caracter a la clase de descarga (línea 231 de pydowntv.py):

video["filename"][indice_parte],

Como necesito que sea diferente para que no se pisen he probado a tocar unas líneas para poder pasarle el nombre del fichero destino como parámetro. Las pongo por aquí por si quisieras incorporarlas o le sirvieran a alguien. Aviso que no sé Python y he ido aprendiendo sobre la marcha así que seguro que es muy mejorable XD Todos los cambios son en el fichero principal pydowntv.py:

Linea 124b
parser.add_option("-N", "--nombre", dest="nombre", help="-N ficheroDestino1.mp4")

Lineas 169 y 169b
"formula1": options.formula1 if options.formula1 is not None else None,
"nombre": str(options.nombre) if options.nombre is not None else None

Lineas 229-235 y 247.253: Se usa el del parámetro si ha recibido alguno
filename = ""
if options.nombre is not None:
    filename = opcs["nombre"]
else:
    filename = video["filename"]
d = uiDescargar.Descargar(
    video["url_video"][indice_parte],
    filename[indice_parte] if video["partes"] > 1 else filename,
    video["tipo"],
    video["rtmpd_cmd"][indice_parte] if video["rtmpd_cmd"] is not None else None,
    video["menco_cmd"][indice_parte] if video["menco_cmd"] is not None else None,
    )

Faltaría adaptarlo para recibir una lista de nombres para descargas múltiples, pero como primera aproximación funciona.

Gracias de nuevo por el trabajo realizado y por compartirlo ;)

Un saludo,
Jorge

**Comment by aabilio** [comment]
He añadido el pequeño soporte sugerido por ti en el último commit: https://github.com/aabilio/PyDownTV2/commit/b3ec55da548f5770aa8161c323629fda5db77b91
