### ISSUE TITLE
Soporte para hogarutil.com

### ISSUE THREAD

**Issue by antonio8909** [aabilio/PyDownTV2#85]
Hola @aabilio ,
Te pido soporte para hogarutil haber si es posible.
Links de ejemplo: http://www.hogarutil.com/tv/programas/karlos-arguinano-cocina/201311/29/index.html http://www.hogarutil.com/decoracion/estancias/bano/201311/como-modernizar-bano-viejo-22573.html

Un saludo y gracias de antemano

EDITO: Se esta buscando una solución más fácil para la descarga de vídeos. Hasta el momento esperen a que salga la solución por parte de un usuario.

**Comment by hotfileuse** [comment]
Me uno a la petición, me interesa el programa de bricomania.

Muchas gracias por el esfuerzo.

**Comment by antonio8909** [comment]
Cierro que ya se esta trabajando en una solución.
Próximamente estará disponible.
Yo mientras estare con otro metodo.
Saludos

**Comment by aabilio** [comment]
PyDownTV no está trabajando en un soporte para Hogarutil. Vuelvo a abrir la issue.

**Comment by antonio8909** [comment]
@denobis tiene ya el programa. cierro la issue porque ya lo tiene y ya va bien

**Comment by aabilio** [comment]
A pesar que @denobis hace un gran trabajo, y ha colaborado muchas veces con pydowntv y otras plataformas, el programa al que haces referencia no forma parte de pydowntv.. Por eso mantengo el hilo abierto hasta que pydowntv soporte de manera oficial este canal. Saludos.

**Comment by antonio8909** [comment]
y lo vais a soportar????

**Comment by aabilio** [comment]
Cuando tenga un poco de tiempo veré qué se puede hacer para la web..

**Comment by Bricomaniaco** [comment]
Hola  antonio8909, de que programa se trata y como lo puedo conseguir?

Saludos
