### ISSUE TITLE
Telecinco

### ISSUE THREAD

**Issue by TOINUSA** [aabilio/PyDownTV2#88]
Hi,
I cannot see " Tierra De Lobos", it says that i do not have the credentials, or something like that. I can see Antena3 with no problem. Can anybody help me?

**Comment by aabilio** [comment]
Url del vídeo?

**Comment by TOINUSA** [comment]
Hola Abilio,

No puedo ver “Tierra de Lobos” http://www.mitele.es/series-online/tierra-de-lobos/temporada-3/capitulo-38/ cuando lo pongo an PyDown, me dice que no tengo credenciales o algo asi, si voy directament a Telecinco, me dice que el vido no esta disponible fuere de Espana, pero eso era asi con Antena 3, y aun asi los podia ver. Me pase igual con algunos, no todos, los videos de RTVE.  Esto es lo que me dice cuando intent ver Tierra de Lobos. Authorization Required

This server could not verify that you are authorized to access the document you requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

No se si hablas ingles, pero mas o menos dice que mi server no esta autorizado para acceder al document porque o tengo los credenciales incorrectos, como por ejemplo la contrasena es mala, o porque me browser no entiende como dar los credenciales necesarios.

Thanks,

Trini Owens

(Office manager)

**Comment by TOINUSA** [comment]
Una cosa mas, uso Google Chrome.

Thanks,

Trini Owens

(Office manager)

**Comment by TOINUSA** [comment]
Perdona Abilio, una cosa mas. He estado viendo “Tierra de Lobos” a traves de miestreno.com. Te lo digo por si esto te allude. Lo que pasa es que ellos no son tan buenos como vosotros, y hoy estan ahi, pero manana alomejor no. Me paso asi con “ Gran Reserva” de RTVE. Ellos estaban dando todos los capitulos hasta que llegaron al ultimo capitulo de la temporada, y por alguna razon no lo tienen. Antes tambien se veian “Amar es Para Simepre” y “ El Secreto de Puente Viejo”, pero ahora nada de nada.

Thanks,

Trini Owens

(Office manager)

**Comment by aabilio** [comment]
El problema es que pydowntv proporciona los enlaces de los que mitele dispone. Si MiTele solo lo ofrece a través de geobloqueo, nosotros no podemos/debemos hacer nada. (el caso de Antena 3 era distinto ya que inicialmente los geobloqueaban, pero permitían acceder al mismo vídeo sin geobloqueo si se sabía cómo..).

Puedes probar a usar un VPN gratuito para aunque solo sea iniciar la descarga. Para Chrome algo como esto: https://chrome.google.com/webstore/detail/hola-better-internet/gkojfkhlekighikafcpjkiklfbnlmeio/details o así (si activas un VPN español para el dominio _.mitele.es_ debería poder dejarte descargar el vídeo (y verlo a través de mitele.es)..

Prueba y a ver qué pasa, nos vas comentando. Saludos.
