### ISSUE TITLE
Falla con Televisión de Galicia

### ISSUE THREAD

**Issue by alvaroordonhez** [aabilio/PyDownTV2#89]
No descarga el video que corresponde con el enlace, si no otro.

Saludos y gracias.

**Comment by aabilio** [comment]
El vídeo que supuestamente es otro, no contiene en ningún momento el primero (el deseado)?

Dame el enlace por favor.

Graciñas ;)

**Comment by alvaroordonhez** [comment]
Pues si. Perdón. No le di tiempo a descargarse de todo.

Lo siento. Borra este issue. Graciñas a vos ;)

**Comment by aabilio** [comment]
Es que ya ha pasado antes y es que crtvg pone cachos de vídeos más largos en su web. En realidad se podría bajar solo el el cacho correspondiente, pero es un poco más complicado ;)
