### ISSUE TITLE
Problema con descarga MiTele

### ISSUE THREAD

**Issue by mardojin** [aabilio/PyDownTV2#92]
http://www.mitele.es/programas-tv/abre-los-ojos-y-mira/temporada-1/programa-16/

Normalmente lo descargo sin problema. Esta semana es la primera vez que me sale esto:

ERROR al recuperar el vídeo. ¿Es una URL válida? An error occured while connecting to the server: Unable to fetch URL: http://www.pydowntv.com/utils/YXRyZXNwbGF5ZXJfcmFuZG9tXzI/1389710341;/nogeo/programa/abrelosojos/t1/c16_ok_1b712fdb.mp4 ;0;0

**Comment by aabilio** [comment]
Ese tipo de problema ya debería estar solucionado (http://www.pydowntv.com/?url=http%3A//www.mitele.es/programas-tv/abre-los-ojos-y-mira/temporada-1/programa-16/). Gracias por reportar.
Saludos.

**Comment by mardojin** [comment]
Muchisimas gracias!

On Tuesday, January 14, 2014 10:27:46 AM, Abilio Almeida notifications@github.com wrote:

Closed #92.
