### ISSUE TITLE
Continuan los problemas con varios programas en mitele.es

### ISSUE THREAD

**Issue by mardojin** [aabilio/PyDownTV2#95]
Sigo sin poder descargar los programs de mitele, aun no puedo descargar pasapalabra y muchos otros. Hoy intente descargar este:

http://www.mitele.es/programas-tv/diario-de/temporada-13/programa-137/

Nada, no puedo descargar nada.

Gracias.

**Comment by denobisipsis** [comment]
Mientras no se arregle en la página de pydown, con el atresdownloader se
pueden bajar.

http://www18.zippyshare.com/v/25019275/file.html

**Comment by mardojin** [comment]
atresdownloader?

On Sunday, January 26, 2014 10:41:58 AM, denobis notifications@github.com wrote:

Mientras no se arregle en la página de pydown, con el atresdownloader se 
pueden bajar. 

http://www18.zippyshare.com/v/25019275/file.html

**Comment by doramas67** [comment]
¡Funciona el atresdownloader, amigos!

**Comment by mardojin** [comment]
Muchas gracias. Se me olvido que esto tambien vale.

On Sunday, January 26, 2014 11:04:06 AM, doramas67 notifications@github.com wrote:

¡Funciona el atresdownloader, amigos!

**Comment by jachsper** [comment]
..tambien para Mac?

**Comment by ismanastic** [comment]
Será que soy extremadamente cortito, pero con lo del multi A3 downloader me pasa lo que nunca me ocurrió con el normal solo para A3. Me dice que no puedo descargar porque me falta un archivo MSVCR110.dll y que por eso no podré descargar, y también algo de AdobeHD me falta. A alguien más le ha salido eso? Es que me bajé ese .DLL y al ir a copiarlo SÍ lo tenía realmente, así que no sé qué diantres pasa.
Gracias!

**Comment by denobisipsis** [comment]
Tiene que ver con el
Visual C++ Redistributable for Visual Studio 2012Descárgate del siguiente
link el update

http://www.microsoft.com/en-us/download/details.aspx?id=30679#

**Comment by ismanastic** [comment]
Primera vez que me pasa...y por qué con el otro no ocurre?
Como diría el padre de Julio Iglesias: "raro raro raro" ^^
Aunque no venga al caso, te hago una pregunta más. Porque creo que va también de códecs y no vi en su día ni una función de MP en este foro :S 
Cuando veo ciertos vídeos en webs, estos se oyen pero no se reproducen más que con una retahíla de rayas...ya te digo que no es con todos, solo a veces. Por ejemplo en resúmenes de partidos. Qué explicación le darías?

PD: y gracias por el enlace, claro. Me lo descargo luego y te digo si me sigue saliendo eso...

**Comment by ismanastic** [comment]
No ha surtido efecto, pero gracias. 
Sigue saliendo el mensaje de Adobe HD no funciona, no podrás descargar f4m

**Comment by denobisipsis** [comment]
1-Borra la carpeta php entera

2-descárgate
http://windows.php.net/downloads/releases/php-5.3.28-Win32-VC9-x86.zip

3-y descomprímelo cambiando el nombre del directorio a "php" sin más

2014-01-27 ismanastic notifications@github.com

**Comment by denobisipsis** [comment]
Tiene que ver con la compilación del último PHP 5.5.8 que es VC11, por lo
que debéis actualizar vuestro visual basic o pasaros a la anterior o
cualquiera que sea superior a 5 y VC9.

2014-01-27 José Luis Lucas Saorín denobisipsis@gmail.com

**Comment by ismanastic** [comment]
Ahora después de comer lo pruebo :)
Comentario de supermegahiperignorante: en el enlace que me acabas de pasar veo "Win32". Eso no influye en nada en si el sistema operativo es de 32 o de 64 bits? Lo digo porque el mío es de 64 :S 
Te informo con lo que sea cuando lo pruebe. Gracias, crack!

**Comment by denobisipsis** [comment]
Debería funcionarte bien, sólo he visto malfuncionamiento en el windows
server pero si es un windows 7 u 8 normal no debe haber problemas. Yo
manejo x64 y el windows 8 y va bien con el php x32.  De todas formas las
versiones php x64 son todavía experimentales

**Comment by aabilio** [comment]
Continuamos en: https://github.com/aabilio/PyDownTV2/issues/94
