### ISSUE TITLE
Conocer como descargar manualmente atresplayer.

### ISSUE THREAD

**Issue by antonio8909** [aabilio/PyDownTV2#97]
Hola @aabilio 
Aunque ya existen muchos metodos para descargar de atresplayer me gustaria saber cual es la manera manual para aprenderla.
Un saludo

**Comment by aabilio** [comment]
Es un tema complejo. Existen muchas maneras de encontrar los enlaces, y que yo sepa ninguno 100% manual.
Puedes ver aquí cómo lo hace pydowntv: https://github.com/aabilio/PyDownTV2/blob/master/spaintvs/grupo_a3.py

Cierro el tema.
