### ISSUE TITLE
Fallo con PyDownTV de web RTVE

### ISSUE THREAD

**Issue by ismanastic** [aabilio/PyDownTV2#98]
Hola,
pues resulta que trato de descargar capítulos de "Amar en tiempos revueltos" con PyDownWeb y ciertos episodios se desincronizan inexplicablemente entre audio y vídeo.
Por ejemplo 
http://www.rtve.es/alacarta/videos/television/amar-tiempos-revueltos1t-capitulo/382264/
en la web de RTVE se ve bien, pero al descargarlo se produce un efecto de que parece que hablen a cámara lenta y con retraso.
Me he encontrado lo mismo por ejemplo en el 2x119
http://www.rtve.es/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t2-capitulo-119/744024/

Sabéis a qué puede deberse?
Gracias de antemano :)

**Comment by denobisipsis** [comment]
Con las calidades altas no pasa

Para el primero

http://mvod.lvlt.rtve.es/resources/TE_NGVA/flv/6/4/1231955466146.flv

y para el segundo

http://mvod.lvlt.rtve.es/resources/TE_NGVA/flv/6/8/1271177524086.flv

bájate esos

En general, para estos capítulos antiguos sustituye del enlace que obtengas
mp4 por flv.

El enlace desincronizado sería

http://mvod.lvlt.rtve.es/resources/TE_NGVA/mp4/6/4/1231955466146.mp4

**Comment by ismanastic** [comment]
:O a mí el PyDownTV no me deja escoger entre calidades...me da el enlace que me da y ya, como siempre, vaya.
La pregunta sigue en pie: ¿por qué se desincronizan? Si el vídeo origen es bueno, el resultado debería ser bueno, porque yo no le hago nada más que descargarlo ^^ 

Pero ahora que lo pienso, a mí cuando me da enlaces de descarga de RTVE, no me da ese http://mvod... sino que me da una ristra de números, por lo que no puedo cambiar el .MP4 por .FLV en ningún lado.
Muy confuso todo en sí, me das excelentes aportaciones pero que a mí no me esa opción :S 
Gracias!

**Comment by aabilio** [comment]
He implementado en PyDownTV los cambios que dice @denobis para los vídeos antiguos. Ejemplo: http://www.pydowntv.com/?url=http%3A//www.rtve.es/alacarta/videos/television/amar-tiempos-revueltos1t-capitulo/382264/

[Commit: https://github.com/aabilio/PyDownTV2/commit/8b831c509ff422530a6172d93f871fffd7ef9bd1]

**Comment by aabilio** [comment]
Fix "vídeos interactivos" reportado a través de Twitter (lo que al final resultó ser un pequeño fallo que no tenía que ver con los vídeos interactivos: https://github.com/aabilio/PyDownTV2/commit/293da80bc9619e64f1f58eb8f7e3686573f6946a
