### ISSUE TITLE
[Petición] Nombre de fichero más descriptivo

### ISSUE THREAD

**Issue by simonbcn** [aabilio/PyDownTV2#99]
Hola,
Cuando descargo el nombre del fichero suele ser un conjunto de letras y números que no me dicen nada. ¿No se podría coger el texto del enlace como nombre del fichero a descargar?

**Comment by aabilio** [comment]
En la medida de lo posible pydowntv intenta poner nombre descriptivos a los archivos.
Para qué urls se está produciendo lo que comentas?

**Comment by simonbcn** [comment]
Cuando bajo cualquier programa de mitele.es pone nombres de fichero del tipo `c20_37e2700f.mp4`.

**Comment by aabilio** [comment]
He estado probando con varios vídeo de MiTele y todos me han dado nombres descriptivos. ¿Podrías, por favor, pegarme algún enlace concreto para saber cuáles son exactamente los que están fallando y por qué? Gracias.

**Comment by simonbcn** [comment]
Olvidé decir que uso el plugin de Firefox 27 en Ubuntu Linux 13.10 64 bits.
Este enlace, por ejemplo: http://www.mitele.es/programas-tv/tu-casa-lo-vale/temporada-3/programa-38/ **>** http://www.pydowntv.com/?url=http%3A//www.mitele.es/programas-tv/tu-casa-lo-vale/temporada-3/programa-38/

**Comment by aabilio** [comment]
OK. Estábamos hablando de dos cosas diferentes. Yo pensaba que me estabas diciendo que utilizabas el script de PyDownTV, y tú me estabas hablando de la versión web.
Sobre lo que comentas, "no puedo realizar nada". Como te dije, pydowntv ya intenta encontrar un nombre para el archivo resultante que tenga que ver con lo que se está intentando descargar, pero esto es para cuando el programa se ejecuta en local a través del script.
A través de la web, solo puedo poner a disposición del usuario el enlace del vídeo en los servidores de mitele. A ese enlace, no le puedo poner que cuando le das a "Guardar enlace como..." te ponga un nombre por defecto (pero sí puedes editarlo tú antes de darle a guardar) es el navegador el que elige el archivo, y la norma general es que sea el nombre del archivo en el servidor (es por eso que los vídeos que bajas tienen esos nombres, es como los llama mitele; observa, para el enlace: http://www.mitele.es/programas-tv/tu-casa-lo-vale/temporada-3/programa-38/ la URL del vídeo en los servidores de mitele es: https://mitelepmd-a.akamaihd.net/1/geo/programa/tucasalovale/t3/c38_fff7a402.mp4?hdnea=st=1391454712~exp=1391458312~acl=/1/geo/programa/tucasalovale/t3/*~hmac=a8097d0665db97fead4068cca6a12ee36c8da383f8a3987154e9495806cf1bd0 y el nombre de archivo que elige el navegador es: c38_fff7a402.mp4, que es justamente el nombre del archivo que le dio mitele. Si te fijas en la URL lo puedes comprobar).
Puede que tengas configurado Firefox para que se descargue el contenido (mp4) a través de un simple clic con el botón derecho y es por eso que no le puedes editar el nombre antes de empezar la descarga.

Vamos a ver, lo que dije antes no es exactamente cierto, sí puedo cambiar el nombre por defecto del archivo descargado en determinados navegadores, pero hacer esto cambiaría el funcionamiento normal de la web (clic derecho > "Guardar enlace como...") y un simple clic izquierdo descargaría el archivo (lo que te comentaba que te puede estar pasando a ti), ya que este es el propósito general del la etiqueta "download" para el elemento "anchor" (el enlace en HTML de toda la vida) que sería la que permitiría a través del valor de la etiqueta (Ej.: <a href="[...]" download="nombre_del_video.mp4") poner un nombre por defecto a ese archivo que se descargaría a través de un simple clic con el botón derecho del ratón. Todo este procedimiento aun no es estándar y no sé qué pasaría exactamente en los navegadores que no lo soporten.

Saludos.

**Comment by simonbcn** [comment]
Ok, vale. 

> Puede que tengas configurado Firefox para que se descargue el contenido (mp4) a través de un simple clic con el botón derecho y es por eso que no le puedes editar el nombre antes de empezar la descarga.

No, si yo descargo haciendo `clic derecho` > `Guardar enlace como...` y cambio el nombre pero lo comentaba por si se podía hacer automático. 

Buen trabajo por este programa/script/etc... va de coña.
